### ISSUE TITLE
Messaging protocol

### ISSUE THREAD

**Issue by AdamISZ** [JoinMarket-Org/joinmarket#10]
Opened to start a discussion.

Here is a first attempt.

(redacted: moved to https://github.com/chris-belcher/joinmarket/wiki/Joinmarket-Messaging-Protocol)

**Comment by AdamISZ** [comment]
Some immediate extra comments: 

* Add extra documentation of the exact message format of each type (fill, auth etc.)
* I agree we have a potentially very important issue with message length leaking info. Needs careful thought.
* Not sure about binary vs ascii format encoding. If we could stick to one encoding at JoinMarket's own messaging layer that would be nice. Then any messaging implementation module (IRC, p2p etc) could convert as required. 

Obviously very much a first draft. I was "inspired" by various thoughts that came up when refactoring the encryption.

**Comment by haarts** [comment]
So what do the fields mean in this `relorder`?
```
!relorder 0 1594202 18352866 100 6.9e-05 ~
```

**Comment by chris-belcher** [comment]
The subreddit, irc channel or bitcointalk thread are better places for questions like that.

The fields are 'oid', 'minsize', 'maxsize', 'txfee', 'cjfee'. The bitcoin amounts are in satoshi, oid is order id, cjfee is the coinjoin fee as a string

**Comment by AdamISZ** [comment]
I created [this](https://github.com/chris-belcher/joinmarket/wiki/Joinmarket-Messaging-Protocol) which is a slightly improved (I hope) version of the above.

**Comment by AdamISZ** [comment]
Docs moved long ago to [this repo](https://github.com/JoinMarket-Org/JoinMarket-Docs), although as it happens right now they badly need updating. Messaging protocol changes for 0.2 in [this gist](https://gist.github.com/AdamISZ/baf93ce2589854a7992383b3c69fae13).
