### ISSUE TITLE
Checking if minsize is greater than maxsize

### ISSUE THREAD

**Issue by btcspry** [JoinMarket-Org/joinmarket#106]
This is a really easy fix.

After experimenting for almost an hour, I learned that in my configuration, I had accidentally set it so that the minsize was greater than the maxsize (ob-watcher.py notifies you of that if you're running it).

It would be a super simple, five minute fix that involves including a check just after line 63:

    if order["minsize"] >= order["maxsize"]:
        print("Minimum order size is greater than maximum order size.  Please  adjust this in the configuration.")

**Comment by chris-belcher** [comment]
I've edited the wiki to mention that it's probably fine to leave the default for most of the configuration values, so changing minsize shouldn't happen.

The yield generator sell-side algorithm is being rewritten at the moment https://github.com/chris-belcher/joinmarket/pull/99

It would definitely be a useful check after the wallet is sync'd to warn the user if they haven't deposited enough bitcoins. https://github.com/chris-belcher/joinmarket/blob/master/yield-generator.py#L131

**Comment by raedah** [comment]
This is a dup of #124

**Comment by raedah** [comment]
This fix was merged in https://github.com/JoinMarket-Org/joinmarket/pull/371 . This can be closed.
