### ISSUE TITLE
Multi-server IRC

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#116]
First suggested by theymos

> To reduce centralization, multiple IRC servers could be used. Makers would idle on all of the servers, and takers would find partners using multiple randomly-selected IRC servers. If any servers are down, Joinmarket should issue a warning, as this may be a DoS attack on the IRC server designed to funnel people to attacker-controlled servers.

Probably best combined with #31 because it will likely be a multi-threaded mutex-branding lock-fest.

**Comment by chris-belcher** [comment]
Actually combing with #31 is a bad idea because smaller coding projects are more likely to actually get done. But for whoever codes this or #31 be aware that eventually the other issue will have to be made too.

**Comment by chris-belcher** [comment]
So this could be made by doing a producer/consumer multithreading model. Each IRC server is communicated with by its own thread which produces incoming messages (like !fill !ioauth and so on). It dispatches them to the consumer thread which is what makes the decisions, calculations, signatures and so on, it runs CoinJoinTX and CoinJoinOrder.

As always, the producer/consumer model is done by lock conditions, wait() and notify() along with a queue accessed from many threads.

And then to do #31 you simply create one more thread which consumes messages off a queue and sends them down sockets allowing for rate limiting.

**Comment by chris-belcher** [comment]
Initial code for this https://github.com/chris-belcher/joinmarket/tree/multiirc

**Comment by AdamISZ** [comment]
Multi-server is now implemented in 0.2 (see the 0.2.0 release notes for some commit numbers), superceding this. We should probably delete the multiirc branch and all the other feature branches too on the main repo, but that's another discussion.
