### ISSUE TITLE
Bug involving different length index_cache list

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#198]
https://www.reddit.com/r/joinmarket/comments/3goqkm/wallettoolpy_indexerror_list_index_out_of_range/

Probably just check the length of the two arrays so it doesnt crash if the version in the wallet.json file is too short.
Tagged as medium for now because I haven't looked at it at all.

**Comment by AdamISZ** [comment]
This is discussed more concretely in #588 and #589 ; linking and closing this one.
