### ISSUE TITLE
Display transaction history of internal wallet

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#200]
Need a script which obtains all the transactions on every address in the wallet, understands them and prints out a list akin to the History tab in Electrum.

It should understand mixing depths and joinmarkets fee so be able to say things like "coinjoin tx to internal mixing depth of 3" and "earned 50000 satoshi"

The Wallet class from common.py does not store the history, which is not needed for the operation of JoinMarket. So this script will have to call the listtransactions RPC call on its own and parse the result.

**Comment by chris-belcher** [comment]
If querying the RPC, it will require txindex=1

If querying an online blockchain explorer it will reveal which addresses are yours to the server

**Comment by the9ull** [comment]
I'm working on this. I'll make only the Blockr version.

> it should understand mixing depths and joinmarkets fee

It does not understand mixing depths nor cj fees now. It can list deposits/withdrawals or/and cj txs. It prints for every tx the local addresses and the moved bitcoins.

I'll make a PR.

**Comment by chris-belcher** [comment]
Would you consider making it work for Bitcoin Core with txindex=1 before releasing?
Having this work only with blockr.io would probably result in a situation that coinbase.com could unmix almost everyone's coinjoins, because all the yield generators will be querying their service whenever they want to see how much money they made.

**Comment by the9ull** [comment]
I understood, I try if I'll have enough time.
I could use testnet network, do you have a testnet JM wallet with an history of txs?

**Comment by chris-belcher** [comment]
I've got testnet wallets you can use, PM me on reddit /u/belcher_ or bitcointalk user belcher and I'll tell you the brainwallet passphrase.
