### ISSUE TITLE
Import private keys to the internal wallet

### ISSUE THREAD

**Issue by the9ull** [JoinMarket-Org/joinmarket#201]
Would be useful the capability of importing private keys into a specific depth of the internal wallet.
Something like:
`wallet-tool.py [-d <depth>] [-k <key>] wallet.json importprivkey`

The key shall be encrypted with the same password of the wallet.

Does this functionality require modifications to external libraries?

**Comment by chris-belcher** [comment]
Another subclass of AbstractWallet could be created for this purpose.

**Comment by chris-belcher** [comment]
I was thinking about this some more today. There are several use cases and now I completely agree with this, I may even write this feature myself.

An example use case: You publish a stealth address publicly (or something similar, maybe your website generates a new donation address for each visitor) and you don't want people knowing how many donations you got when you combine all of them when sending to some address. A solution to that might be to send each donation address from a different mixing level in a tumbler.py process. That would be made much easier if you could import private keys.

In that case don't create a another AbstractWallet subclass, just add the feature to the existing Wallet.

**Comment by chris-belcher** [comment]
When interfacing with Bitcoin Core, there will be another label called something like joinmarket-wallet-imported which all joinmarket wallets can use, since it makes no sense tying imported keys to the hash of the HD seed that has nothing to do with them.

Also make sure the imported keys are not printed when it all crashes, like how the HD seed is omitted now.

**Comment by chris-belcher** [comment]
Implemented here https://github.com/chris-belcher/joinmarket/commit/cb871b43831d164daee5dc843dd34b585ba77757

**Comment by the9ull** [comment]
I love you
