### ISSUE TITLE
CoinJoin / JoinMarket privacy

### ISSUE THREAD

**Issue by eragmus** [JoinMarket-Org/joinmarket#211]
Question 1:

Is there research available or peer review on CoinJoin / JoinMarket, in terms of how effectively it makes private the transaction graph? For instance, the cryptonote protocol has been peer reviewed by Surae Noether, and found to conserve privacy although with non-zero amount of info still available for analysis, and with a few drawbacks e.g. novel crypto that has not been tested enough yet, and new algorithm as an alternative to Bitcoin's PoW but which has not been explicitly described or analyzed (so can't be understood or tested properly). Meanwhile, privacy achieved via a zero-knowledge system has zero info available for analysis (thus achieving the true epitome of privacy).

Question 2:

Where does CoinJoin / JoinMarket find itself on the privacy spectrum? I suppose it does not produce completely unlinkable transactions (zero knowledge style), so it still relies to some extent on 'plausible deniability', but where does it lie? Is it more private than cryptonote, or less (I'm guessing less)? If less, how much less (significantly less? or, non-significantly less?)? Furthermore, if plausible deniability is the result, then is that truly strong enough as a privacy guarantee or just an aid to deter casual analysis? Basically, I'd love a link, if there is one, to a competent peer review, similar to that done by Noether.

To clarify the previous paragraph, perhaps we can assume 4 levels of privacy: a) privacy no one can break, b) privacy NSA can break, c) privacy local law enforcement can break, and d) privacy your friend or neighbor can break. A zero knowledge system can be categorized as (a), cryptonote can be categorized as (b), and current bitcoin's protocol can be categorized as (c) mostly due to the pseudonymous nature of cryptic addresses (no real names linked by default). -- On that scale, where would CoinJoin lie?

---

Another clarification please. With JoinMarket, one party's bitcoins maintain liquidity, while the other party's bitcoins metaphorically 'dip into that pool' and emerge unlinked from their prior transaction history. At this point, that party has achieved privacy, if we consider for this assumption for the sake of argument. On the other hand, Wikipedia describes CoinJoin as: "When you want to make a payment, find someone else who also wants to make a payment and make a joint payment together. In case of such a joint payment there will be no way to relate input and outputs in one Bitcoin transaction and thus the exact direction of money movement will remain unknown to the third party." So, with the original idea of CoinJoin, all transactions made by a user will stay private. However, the scope of JoinMarket is narrower, as it only applies CoinJoin to mix bitcoins but not in the process of making a transaction.

Question 3:

So, if after a JoinMarket transaction a party makes consistent daily transactions for the next 30 days, then is it not true that the newly gained privacy will again gradually disappear? If so, then would it require another JoinMarket transaction to restore privacy? This sounds a bit clunky... has their been any discussion on how to make the process more automated, so as to consistently maintain privacy of the transaction graph? I'd imagine that only an asynchronous solution is viable (like JoinMarket), while a more synchronous solution (in the vein of performing a CoinJoin every single time a transaction is made) is impractical. But, is that assumption true? And, are there ways to improve this process?

e.g. Setting to automate CoinJoining of user's balance every 'x' days (where 'x' is a number that represents an optimal yet reasonable amount of time required to maintain 'decent' privacy -- could theoretically expand 'x' to y and z, where y = 'high' privacy and z = 'good' privacy). Suppose x was 30 and we assume a user's balance of 10 bitcoins, then the current order book's rates imply 0.001% fee to CoinJoin that balance every 30 days (1 month), and hence a yearly fee of 365 / 30 * 0.001% = 0.012% to maintain 'decent' privacy. -- So, 10 bitcoins would become 10 - (.012 / 100 * 10) = 9.9988 bitcoins after 1 year, and 9.988 bitcoins after 10 years. That doesn't seem bad at all, and hence viable at achieving the goal of 'decent' privacy, especially now that we have hypothetically automated the CoinJoins (which also provides the liquidity providers with increased ROI and predictable ROI, and hence strengthens JoinMarket's market) and simultaneously shown that long-term cost remains low.

**Comment by chris-belcher** [comment]
1) No papers to my knowledge about JoinMarket. Some papers published about coinjoin, but they were not necessarily relevant to JoinMarket (were about SharedSend or just misunderstood the coinjoin concept)

2) There isn't a link that I know of. The privacy is probably less strong than cryptonote.
JoinMarket would probably lie closer to b) than c)

With JoinMarket you can do just-in-time coinjoins as well as batch mixing. Also, the party that maintains liquidity might also want to do a transaction of their own, but they provide liquidity because they have time available to be able to wait.

3) Related to your misunderstanding about JoinMarket only doing asynchronous mixing. When written, the Electrum plugin and Bitcoin Core integration would do just-in-time coinjoins, where all transactions become coinjoins transparently to the user.

**Comment by eragmus** [comment]
Thanks Chris.

So, re: 3, yeah I assumed it was only asynchronous. When you say "just-in-time", does this mean every user's transactions will automatically 'dip' into JoinMarket's liquidity pool to do a CoinJoin? By the way, how long would that take, vs. a non-CJ transaction that we can say would otherwise take say 1 second?

**Comment by chris-belcher** [comment]
> When you say "just-in-time", does this mean every user's transactions will automatically 'dip' into JoinMarket's liquidity pool to do a CoinJoin?

Yes. You can do this today using the sendpayment.py script

> By the way, how long would that take, vs. a non-CJ transaction that we can say would otherwise take say 1 second?

Not that long. If your script idles in the IRC channel for a long time it could complete the transaction in a similar amount of time to a normal bitcoin transaction.

**Comment by adlai** [comment]
http://fc15.ifca.ai/preproceedings/bitcoin/paper_5.pdf

**Comment by chris-belcher** [comment]
Yep I remember that paper.

This is their method to detect coinjoins.

    To attempt to understand the growing popularity of coinjoin transactions, we looked at how many transactions matched a rough pattern of what we might expect coinjoins to look like. **We defined this pattern as any transaction having more than five inputs and more than five outputs**, and looked at how many transactions matched this pattern (which is admittedly only roughly correlated with coinjoins, but as coinjoins are indistinguishable from other transactions we cannot do better than an approximation)

Unfortunately that's a terrible heuristic to detect coinjoin txes. It would mean [this](https://tradeblock.com/bitcoin/tx/92a78def188053081187b847b267f0bfabf28368e9a7a642780ce46a78f551ba) and [this](https://tradeblock.com/bitcoin/tx/5dc8254ff7090efa8aa07348530d47a09b67d14d1315ffd22d1b852bf93fb8db) are not coinjoins and [this tx](https://tradeblock.com/bitcoin/tx/b6cfd7551620fb1341e78a406ec95cfcc2f7ff07518f835b005cddc8608a5a46) from an exchange to process batch withdrawals is.

**Comment by AdamISZ** [comment]
This seems like a general question/discussion about JM properties which has been answered, so closing.
