### ISSUE TITLE
tumbler Insert New Address can be missed amongst other prints

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#239]
When Insert New Address is used in tumbler, it will continue to print out other crap like messages from the IRC channel, which means users might not notice they have to actually do something now.

Probably the simplest way to fix is to disable IRC printouts while waiting for a new address to be given.

**Comment by tailsjoin** [comment]
This problem exists on sendpayment.py also when asking to confirm orders. It's rare, but I had an instance where the accept prompt came up just as a group of makers reanounced their orders. I could see a new user being really confused if even I announcement came right then (which I've had quite a few times).

**Comment by chris-belcher** [comment]
https://github.com/chris-belcher/joinmarket/commit/2769ee80cab4af0971034020c1dcdc5a9b00e282

**Comment by chris-belcher** [comment]
Debug should also be silenced during the sendpayment query as @tailsjoin writes

**Comment by chris-belcher** [comment]
While fixing #400 I realise this issue is again unfixed. Since the new method of logging does not use debug_silence.

**Comment by chris-belcher** [comment]
Fixed again https://github.com/JoinMarket-Org/joinmarket/commit/671edccd9edfa2bcb464dca64fecbd97aadb770f
