### ISSUE TITLE
Write guides for wallet developer and bitcoin websites.

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#251]
Right now the wiki only has guides for individual users, but they are not the only ones who use JoinMarket.

Bitcoin institutions like exchanges and marketplaces can use it to make their hot wallets coinjoined and thus better hide their internal workings.

Wallet developers might want to implement JoinMarket for their wallet.

**Comment by AdamISZ** [comment]
[This](https://github.com/JoinMarket-Org/joinmarket/wiki/Joinmarket-Messaging-Protocol) goes towards this goal, as partly does the code documentation started in #336.

**Comment by adlai** [comment]
Maybe we can close this, now that we have [a separate repo for developer documentation](https://github.com/JoinMarket-Org/JoinMarket-Docs/blob/master/High-level-design.md)?
