### ISSUE TITLE
Changing tabs for spaces and structural updates

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#254]
@ghtdak has used a tool to change tab indentation for spaces without breaking git blame. As well as some other stuff, like changing lib/ into joinmarket/ and making it a python package instead of it being added to path.

https://github.com/ghtdak/joinmarket/commits/development

Apparently this gets combined into the repos with `git branch -f master master-yapf`

**Comment by ghtdak** [comment]
I'm writing up what I did in the project which really doesn't exist. I had to name it though, so it now has a wiki

https://github.com/ghtdak/gitreformat/wiki

**Comment by ghtdak** [comment]
The code at 
https://github.com/ghtdak/joinmarket/commits/development 
is both a history / blame preserving yapf reformat and a fix of the imports including the creation of the joinmarket module, replacing "lib"

All the path manipulating python is replaced in favor of the usual standard module inclusion.

**Comment by AdamISZ** [comment]
This has been addressed by #340 and #345.
