### ISSUE TITLE
Wallet should auto-pay only to the change address branch

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#283]
The change and receive address branches function the same when being spent from, they are both parts of the mixing depth.

When a wallet is generating an address to send to itself, it should send to the change address branch. It has happened that a user of yield-generator has sent new coins to an address on the receive branch. When the yield generator requires a new address it will generate the same address(!) Leading the address re-use.

Just a few lines of editing. Should rename the two branches, perhaps to "internal" and "external".

@adlai 's idea originally.

**Comment by AdamISZ** [comment]
Addressed by #368.
