### ISSUE TITLE
'JsonRpcConnectionError' when using sendpayment.py

### ISSUE THREAD

**Issue by MMMonsterrr** [JoinMarket-Org/joinmarket#292]
I keep getting the following error when trying to use sendpayment.py:

```
File "/home/someone/joinmarket/lib/blockchaininterface.py", line 558, in pushtx
    except JsonRpcConnectionError:
NameError: global name 'JsonRpcConnectionError' is not defined
```

My joinmarket.cfg has `blockchain_source = bitcoin-rpc`

I can display the wallet with wallet-tool.py just fine though, so the connection to bitcoind seems to be working. I've also used sendpayment.py successfully before with no problems. The only thing that has changed since then on my side is that I used `-m 7` on that wallet to increase mixlevels to 7.

**Comment by chris-belcher** [comment]
Slightly crazy that this bug hasn't come up before https://github.com/chris-belcher/joinmarket/commit/6712269dbd91992c1ac7a56fb4320fec3366b54e
