### ISSUE TITLE
Non Alphanumeric Characters In The rpc_password

### ISSUE THREAD

**Issue by mclstr** [JoinMarket-Org/joinmarket#295]
There is no mention in the doc about having to limit the "rpc_password" to alphanumeric characters.

It just says to use a secure password and I would think most people would want to include some non-alphanumeric characters in the password.

It's not a problem as long as the configuration docs made that known.

**Comment by AdamISZ** [comment]
I reproduced this here on regtest. Looking into it, thanks.

**Comment by AdamISZ** [comment]
In the absence of a response, and not seeing an issue here, closing this.
