### ISSUE TITLE
User sends orderbook response to channel, not via PM

### ISSUE THREAD

**Issue by dcousens** [JoinMarket-Org/joinmarket#299]
Happens quite a lot when the attack https://github.com/chris-belcher/joinmarket/issues/298 is performed.

**Comment by dcousens** [comment]
Seems to affect other commands as well

**Comment by tailsjoin** [comment]
I just logged in to make an issue about this. It actually knocked me from the irc and my bot had to reconnect. Maybe just coincidence, but I doubt it. [log](https://paste.debian.net/plainh/e4c08bad)

**Comment by AdamISZ** [comment]
See my comment at the end of #361.
