### ISSUE TITLE
Outgoing messages priority queue

### ISSUE THREAD

**Issue by dcousens** [JoinMarket-Org/joinmarket#300]
Rather than sending the raw text as it happens, we should build an out-going message priority queue.
It is emptied at a constant rate so as to avoid DoS'ing the client and public/broadcast/spam messages are set to a low priority.

Combined with a user scoring system [manages priority for each nick] which penalizes unexpected messages,  this should resolve most of the [known] DoS issues.

**Comment by chris-belcher** [comment]
Similar to #31

I agree this could help.

Sorting the message types by priority is good too. Ping replies to the server are highest priority, then replies to an existing coinjoin deal, then replies to !orderbook have the lowest priority.

**Comment by ghtdak** [comment]
Bitcoin core has similar issues.  While this can be handled at the application layer, an alternative approach is to use Linux's built in traffic shaping mechanisms.  Core includes a script in [contrib/qos](https://github.com/bitcoin/bitcoin/tree/master/contrib/qos) which will '*do the right thing*' and is provided to mitigate these issues.

If it is necessary to prioritize some traffic, the rules are a bit trickier.  I use [`Shorewall`](http://shorewall.net/) for firewalling, shaping etc. It's basically a much more involved version of the kinds of things `contrib/qos/tc.sh` is doing.

**Comment by AdamISZ** [comment]
Added this to milestone with the intention it will be addressed at least to the extent that non-malicious usage patterns do not lead to kicks. I think it would have to be at the application layer.

We can perhaps make another issue later to plan for more sophisticated handling.

**Comment by ghtdak** [comment]
I obviously missed that this was an IRC flood / kick issue, not at the network level (doh!)

Until code is written / changed, a relatively easy fix is inserting an IRC bouncer between Joinmarket and the server.

[`ZNC`](http://wiki.znc.in), for example, has a [configuration entry](http://wiki.znc.in/Configuration) for FloodRate set by default to 1 second.

**Comment by AdamISZ** [comment]
Addressed by #366 in line with previous comments.
