### ISSUE TITLE
Properly import private keys from electrum json file

### ISSUE THREAD

**Issue by lacksfish** [JoinMarket-Org/joinmarket#332]
This being a future feature I'd love to implement, what would be the best way to go about this?

Joining all inputs into a transaction with one output address to fund the wallet is a major privacy concern already. Importing keys could be an alternative solution.

The issue: The exported electrum json/csv file contains all private keys, including 0 BTC change addresses.

This thread would be to discuss several importing approaches such as:
- Importing all keys (maybe >100) into mixing depth 0
- Checking for non zero funds on address and then import only those
- Other approaches

Any ideas and concerns welcome.

**Comment by lacksfish** [comment]
As electrum is only using compressed privkeys (and JM only using uncompressed ones) I don't see how this feature can be added for the time being.

**Comment by AdamISZ** [comment]
No, Joinmarket uses compressed privkeys, although of course the concept is slippery as a "compressed" privkey is merely a representation; the addition of the byte \x01 to the end of the 32 byte scalar. The important point being that it reflects the use of compressed pubkeys, which we do use. Additionally, as I guess you know, you can *export* your keys from joinmarket to electrum using the -p option to wallet-tool. The privkeys are shown in WIF compressed format.

I think it's a good idea to figure out how to import, I like it.

**Comment by lacksfish** [comment]
> No, Joinmarket uses compressed privkeys

Sure. Sorry, I mixed that up.

Full support for uncompressed privkeys and their associated public keys (and corresponding addresses) would be a very nice thing. Still looking at how to approach this.

**Comment by adlai** [comment]
We have support for importing compressed keys into the wallets. I haven't used this yet, although I tried once with an uncompressed key and it didn't work, so there's still a bit more to do here.

**Comment by dreboli** [comment]
yeah, when trying to import uncompressed priv keys the error message is
```
Traceback (most recent call last):
  File "wallet-tool.py", line 244, in <module>
    vbyte=get_p2pk_vbyte()).decode('hex')[:-1]
  File "/home/pi/joinmarket_0.1.3_develop/bitcoin/secp256k1_main.py", line 138, in from_wif_privkey
    raise Exception("Compressed private key is not 33 bytes")
Exception: Compressed private key is not 33 bytes
```

**Comment by AdamISZ** [comment]
That is deliberate on my part; whereas the comment in the earlier version of the code was 'Uncompressed not supported yet', I felt it better not to support it at all. I wanted to keep the paths as strict and narrowed down as possible in such a critical/dangerous area. 

Which program is providing uncompressed keys? The only reason to use an uncompressed privkey is to generate an uncompressed pubkey, which is as far as I know an entirely undesirable thing.

**Comment by dreboli** [comment]
Electrum, it exports priv keys in uncompressed form.

**Comment by AdamISZ** [comment]
Right; sorry I didn't read the whole comment thread, it has already been mentioned. Well, given that (I wonder why?), I wouldn't be averse to someone opening a PR to accept uncompressed. The difference is trivial at the raw level, but of course we have to be ultra paranoid about this, test cases are essential.

**Comment by chris-belcher** [comment]
Uncompressed signatures and pubkeys make that input stand out as special in the coinjoin and could be used for unmixing.

**Comment by dreboli** [comment]
I converted the keys by pasting the uncompressed priv keys to filename and used all my programming skills to write this:
```
from __future__ import print_function
from bitcoin import *
with open('./filename') as f:
    content = [x.strip('\n') for x in f.readlines()]
for elem in content:
    comp=encode_privkey(elem, 'wif_compressed')
    print(comp, end=',')
```
then imported the list with wallet-tool.

Problem: the addresses listed under `import addresses` with wallet-tooly.py are different from the addresses originally exported from Electrum.
Why is this and what to do to solve this?

**Comment by dreboli** [comment]
I took the uncompressed priv keys exported from electrum, used this script to get the compressed wif key format:
```
from __future__ import print_function
from bitcoin import *
with open('./filename') as f:
    content = [x.strip('\n') for x in f.readlines()]
for elem in content:
    comp=encode_privkey(elem, 'wif_compressed')
    print(comp, end=',')
```
then imported the keys with wallet-tool.py

But wallet-tool lists the compressed bitcoin addresses under imported keys, while Electrum used uncompressed addresses so the imported addresses are different than the ones exported from Electrum.
Any way to solve this other than sending the coins from Electrum to JM wallet?

**Comment by AdamISZ** [comment]
> Uncompressed signatures and pubkeys make that input stand out as special in the coinjoin and could be used for unmixing.

It's a good point but one of that category "if you're the only one using it it's a privacy leak" - if everyone did it, it wouldn't. I think a more fundamental point perhaps is it's a considerable space wasteage.

> Why is this and what to do to solve this?

Joinmarket is assuming that all stored privkeys (including those imported) are to be interpreted as compressed (actually only the 32 byte raw key is stored in the wallet). Electrum, as I have just discovered by experiment, used uncompressed private and public keys pre-version 1.9. Even if you're using an updated Electrum version, what matters is the version when the wallet was created.

So finally, how would you import uncompressed. Well first, yes, send the coins, it's a far better idea. To import uncompressed WIF using code you can do:

```
priv = btc.from_wif_privkey("WIFKEY", compressed=False)
```

If you then want to create the address corresponding (using **uncompressed** pubkey) do just:

```
btc.privkey_to_address(priv)
```

This will give the same address as an Electrum wallet which was created pre-1.9 (at least, that's what I report and lines up with what I was told over IRC #electrum)

You can also create the address corresponding to the compressed pubkey by doing `btc.privkey_to_address(priv+'01')`

I don't recommend doing any of this :)

**Comment by dreboli** [comment]
Okay, thanks for your answer!
I think I'll go with sending the coins.

**Comment by lacksfish** [comment]
Importing uncompressed private keys would perhaps not be a privacy concern. Upon spending the coins, the pubkey would be revealed to be 65 bytes instead of the compressed size of 33 bytes, which is bad at first. But then, all mixing transactions onwards would be signed by compressed private keys.

The first coinjoin would be leaking the usage of uncompressed keys, but all transactions onwards wouldn't. So I am wondering if this could turn out to be not much of a privacy issue.
