### ISSUE TITLE
Indexing with booleans in common.py

### ISSUE THREAD

**Issue by AdamISZ** [JoinMarket-Org/joinmarket#333]
This is funky:

https://github.com/chris-belcher/joinmarket/blob/master/lib/common.py#L426-L430

Any reason not to use 0/1 instead of false/true? I can PR but busy with something, just dropping it here.

**Comment by raedah** [comment]
Why would you want to use an int instead of a boolean where only a boolean is needed?

You could specify it for clarity.
get_new_addr(mixing_depth, forchange=False)

**Comment by AdamISZ** [comment]
Because t's a list index. Basically it's calling index[True] and index[False]. Not saying it's wrong, but it's not normally done like that.

**Comment by AdamISZ** [comment]
And confusingly enough, "index" in my code there is a list :) Note, it's not a dict.

**Comment by AdamISZ** [comment]
Clearer I hope:

    x = [4,5,6]
    x[False]
    4
    x[True]
    5

**Comment by raedah** [comment]
I see what you are saying. Boolean works fine for me though. I dont have a preference either way.

**Comment by chris-belcher** [comment]
No reason, change it to 0/1 if you like.
Who knows what I was thinking way back when I wrote this ¯\_(ツ)_/¯
Maybe wanted to emphasize that only two values are allowed so someone wouldn't try putting in higher integers. If we ever add issue #84 then the forchange will need to allow other values.

I suppose `index` could be renamed to `key_pointer` or `address_pointer` ?
