### ISSUE TITLE
Blame preserving reformat (was PR #340)

### ISSUE THREAD

**Issue by ghtdak** [JoinMarket-Org/joinmarket#345]
This [PEP-8](https://www.python.org/dev/peps/pep-0008/) / [Google Yapf](https://github.com/google/yapf) reformat preserves annotations (git-blame) and was pulled from [ghtdak/master-yapf](https://github.com/ghtdak/joinmarket/tree/master-yapf) as [joinmarket/develop](https://github.com/JoinMarket-Org/joinmarket/tree/develop) for evaluation.  It contains no code changes other than Yapf reformats and is one step in Joinmarket refactoring (see #343)

[ghtdak/master-yapf](https://github.com/ghtdak/joinmarket/tree/master-yapf) is a parallel commit history where PEP-8 reformatting has been applied prior to the mirror's commit.  See: https://github.com/ghtdak/gitreformat/wiki

A prior attempt to squash the parallel history into a single commit for merging into Joinmarket was unsuccessful (see [this](https://github.com/JoinMarket-Org/joinmarket/issues/343#issuecomment-161939573)) and was a bad idea anyways.  The new approach, should this "new/better/different" version of history be accepted, develop == master-yapf will replace master as opposed to the typical "merge" of pulls / development branches.

[joinmarket/develop](https://github.com/JoinMarket-Org/joinmarket/tree/develop) references commit 62855094476fecaf8a50c17b274fa3eb1cd370dd which is a yapf of [joinmarket/master](https://github.com/JoinMarket-Org/joinmarket/tree/master) when it referred to commit 2ef37996f90d3c4ea3ca7880a1619a182e710e67 of 11/25/2015.  We will periodically update [joinmarket/develop](https://github.com/JoinMarket-Org/joinmarket/tree/develop) to mirror development on [joinmarket/master](https://github.com/JoinMarket-Org/joinmarket/tree/master)

**Comment by AdamISZ** [comment]
This is done, thanks.
