### ISSUE TITLE
Tumbler.py crashes after "Got invalid maxsize: -12345 from..." 

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#348]
Could get up to 9 successful TX-es in a row after a couple of tries.
Any way to solve this other than blacklisting nicknames by changing the code then hope it will run this time?

Crashing with:
error: {"code":-5,"message":"No information available about transaction"}

I have similar issues with sendpayment when trying to make joins with more than 5 participants, it crashes many times with
error(32, 'Broken pipe')
Isn't there a better way to handle these cases without crashing?

**Comment by chris-belcher** [comment]
For your first problem, I don't think we have enough information to tell. Post the logs.

Your second problem is probably #31

**Comment by adlai** [comment]
Unless @dreboli objects, I suggest closing this issue.
