### ISSUE TITLE
Yield generator and connection issues

### ISSUE THREAD

**Issue by the9ull** [JoinMarket-Org/joinmarket#351]
Every time my connection go down for a while my yield generator [dies and quit](https://github.com/JoinMarket-Org/joinmarket/blob/master/yield-generator.py#L152).
I wrote some [dirty code](http://pastebin.com/Xv0cZQB3) to manage this issue, but I'm asking why the yield generator dies for a common error. Maybe mine is the worst connection of the world.
Btw I think that my code leaves some old thread alive around because I get some errors on the command line. So: how should I manage this issue? Should this code (after fixing) be submitted here?
Thanks!

**Comment by AdamISZ** [comment]
Right now I can only comment that it was always intended that the yieldgenerator should be robust to connection failure (pretty sure it is in the case of losing IRC, not sure about full net connection loss - I thought that was also OK, I might be wrong).

**Comment by raedah** [comment]
I think they might be referring to this error.

Traceback (most recent call last):
  File "yield-generator.py", line 365, in main
    irc.run()
  File "/home/r/bin/joinmarket/lib/irc.py", line 470, in run
    self.sock.connect(self.serverport)
  File "/home/r/bin/joinmarket/lib/socks.py", line 366, in connect
    self.__negotiatesocks5(destpair[0],destpair[1])
  File "/home/r/bin/joinmarket/lib/socks.py", line 235, in __negotiatesocks5
    raise Socks5Error(_socks5errors[min(9,ord(resp[1]))])
Socks5Error: 'TTL expired'

**Comment by chris-belcher** [comment]
Same as https://github.com/JoinMarket-Org/joinmarket/issues/452 it seems

**Comment by AdamISZ** [comment]
#452 was closed so closing this.
