### ISSUE TITLE
[new-yieldgen-algo] Lower cjfee when a mix depth is void

### ISSUE THREAD

**Issue by the9ull** [JoinMarket-Org/joinmarket#358]
When one of the mix depths doesn't have a positive balance the cjfee are lowered because the highest one is cutted off by the orders. I think that should be used the highest cjfees.

Mix depth 0 | Mix depth 1 | Mix depth 2
------------ | ------------- | -------------
.2% | .1% | .05%
10Ƀ | 2Ƀ | 0Ƀ

Now the yield generator orders are:

Balance | Fee
------------ | -------------
10Ƀ | .1%
2Ƀ | .05%

**Comment by chris-belcher** [comment]
I think you're right. This is within the spirit of the new-yieldgen-algo as I intended.

BTW, new-yieldgen-algo probably needs a new name given that we have many of them now.

**Comment by the9ull** [comment]
fixed-steps-fee? — From my low knowledge of English

**Comment by raedah** [comment]
I can take this one.

**Comment by raedah** [comment]
This fix was merged in https://github.com/JoinMarket-Org/joinmarket/pull/371 . This can be closed.
