### ISSUE TITLE
yield-generator-deluxe misbehaviour

### ISSUE THREAD

**Issue by riclas** [JoinMarket-Org/joinmarket#392]
hi, i got another interesting edge case for @raedah 

http://pastebin.com/8HkP2gLs

**Comment by AdamISZ** [comment]
Not directed to me but I'm curious: what's the actual problem? The pastebin just shows a bunch of settings, right?

**Comment by riclas** [comment]
and the orders that ygdeluxe created for me.
there are 2 issues:
- order 7 has a cjfee lower than orders 3, 4, 5 and 6 (i already reported this to him yesterday with another log)
- order 5 and 6 has a higher cjfee than the max on the settings

**Comment by raedah** [comment]
@riclas This should fix it. Can you replace this function and verify?

```
def fib_seq(low, high, num, upper_bound=False):
    x = []
    if upper_bound:
        num += 1
    else:
        x.append(low)
    fib_sec = (high - low) / decimal.Decimal(fib(num))
    for y in range(2, (num + 1)):
        x.append(low + (fib_sec * fib(y)))
    return x
```

**Comment by riclas** [comment]
seems to work nice now, good job.
