### ISSUE TITLE
yield-generator-deluxe.py txfees causing negative net satoshis

### ISSUE THREAD

**Issue by grubles** [JoinMarket-Org/joinmarket#395]
It seems that using -deluxe.py with the default configuration results in loss of satoshis. 

`2016-01-19 19:44:54,717 [Thread-3    ] [DEBUG]  earned = -158`

min_revenue setting: 
`min_revenue = random.randrange(txfee_low, 12000)  # varied`

**Comment by raedah** [comment]
An quick fix would be changing txfee_low to txfee_high.
Thats going to make all the offers on the lower txfee side more expensive.
But no more satoshi loss.
