### ISSUE TITLE
Malformed message causes all bots to crash

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#400]
@raedah discovered a bug that causes all bots in the channel to crash.

It's fixed here, https://github.com/JoinMarket-Org/joinmarket/commit/fb624cc39d703dd2f6266f95ac30e04d82c3b24b

I think a new release needs to be created, JM_VERSION needs to be incremented and an alert set asking people to update. Then some information posted on forums/reddit/twitter.
I would do this now but its 3am, I'll do it tomorrow if I'm the first up.

**Comment by raedah** [comment]
I have 3 bug fix pull requests for master that are ready to go. I suggest getting these into the next release as well.

**Comment by AdamISZ** [comment]
@chris-belcher I agree about the JM_VERSION and alert, it'll be good to nag users to upgrade (if crashing doesn't convince them). Re your IRC questions, the tag is annotated, yes. So this will be v0.1.2
@raedah ok message received.

**Comment by AdamISZ** [comment]
IIUC from looking at the commit history, it seems  you pushed the same fix to master and to develop separately? If so, I guess the right thing to do is: 

1. remove the last 3 commits from master
2. merge raedah's 3 bug fix PRs for yg-deluxe
3. add a commit for the JM_VERSION change
4. add release notes and tag that commit
5. merge from dev to master

seem right?

**Comment by chris-belcher** [comment]
Just found that the new debug() code does not print out an alert before every line if it exists. So our capability to send alerts is gone. Luckily anybody can easily crash an unupdated bot so they'll get the message eventually.

**Comment by chris-belcher** [comment]
It's worth justifying the alerts system since a few on IRC were against it. The last time we used alerts was to ask people to update the fix to the BIP66 signing bug. It would produce an invalid signature 1 out of every 256 times, so a maker would be unlikely to notice. The only alternative is asking people to constantly hang around on reddit or internet forums, reading mundane questions and chit-chat just so on the off chance a serious bug comes out they can update. The alert system is more respectful to people's time. It doesn't do anything apart from send a textual message to users.

**Comment by chris-belcher** [comment]
New release made. Alert sent. Forums/reddit posts written.

In the next few days or weeks we can start saying "!cancel"
