### ISSUE TITLE
Tool for making debug logs private

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#403]
JoinMarket's debug logs are very useful, but because they contain private information so users are often unwilling to share them publicly.

There should exist a script which scans debug logs and replaces possibly-sensitive information with placeholders that allow debugging but don't ruin privacy.

For example, addresses and UTXOs are replaced with placeholders. Timestamps are made relative where the debug log starts at T and all other times are T+00:02:30 or whatever.

**Comment by adlai** [comment]
Thoughts from IRC:
- txids, utxos, and addresses should be replaced by placeholders such as `UTXO_001`, `TXID_002`, `1BTCDoUBLERjusttryandseeXXXXZHoLtX`, etc.
- amounts should be removed by default, with no information leaked (other than maybe a single uniform `AMOUNT` placeholder). there can be a flag for leaving them, or replacing with unique tokens, but the default should be to remove entirely.
- timestamps should be removed by default, but there should be a flag for leaving a relative timestamp.
- counterparty identities (currently, IRC metadata) should be removed by default, with a flag for irreversible tokenization.

**Comment by chris-belcher** [comment]
Work-in-progress version helped solve this #442

**Comment by dreboli** [comment]
Might not hurt to censor wallet names too
For example from:
````
rpc: getaddressesbyaccount ['joinmarket-wallet-123dbc']
````

**Comment by chris-belcher** [comment]
That name has no private information, it's merely the first few bytes of the hash of part of your wallet.

**Comment by dreboli** [comment]
I was thinking about a scenario where an attacker gets hold of the wallet name (compromises the machine where the watch-only wallet runs or gets access to log files) and searches for the wallet name on the net will reveal additional info (github account name, additional logs etc.)

Not life threatening but since it wouldn't hurt it's better to scrub anything just in case in my opinion.

**Comment by chris-belcher** [comment]
First version merged into develop here https://github.com/JoinMarket-Org/joinmarket/commit/80ed20dc1a94d3d59b3f8a05da779d94a0ee1f57

**Comment by chris-belcher** [comment]
Closing since a first version exists
