### ISSUE TITLE
Move yieldgen configuration to joinmarket.cfg

### ISSUE THREAD

**Issue by raedah** [JoinMarket-Org/joinmarket#421]
This issue is to replace broken pull request #246. This will discuss which options will be available and how it will integrate with the yield generator code. When yg configuration is done in the joinmarket.cfg, there would ideally be only a single ./yield-generator.py for the user to execute. The top level yield-generator.py should be simplified, with all yg variations (mixdepth, deluxe) moved into a shared library in the joinmarket module where they are hidden from the user. Accessing the possible yg configurations would be done via the joinmarket.cfg. The shared library will allow for the removal of duplicate code that is currently in the different yg variations.

The idea behind the basic yg is to create a single offer. The idea behind yg-mixdepth is to create offers equal to the sizes of the mixdepths (usually 5) with an set of cjfees to apply to each. The idea behind the yg-deluxe is for the user to define how many offers they want, at what sizes, and what fees. So we should offer a config that allows for these different cases. 

Between the current basic, mixdepth, and deluxe yg's, there are many different variables and many different configurations. Basic is simple and minimal, while deluxe has many options and is highly customizable. Ideally the configuration should easy to grasp for new users but be extensible for advanced users. The simple case would just be a few config lines, but the advanced case would allow a broad array of configuration cases that could be tweaked for explicit detail.

These config options will fall into two classes. Options that apply to all yg setups, and options that only apply to specific yg setups. 

Deluxe is currently using  profit_req_per_transaction = 1  while basic is using  minsize = int(1.2 * txfee / float(cjfee)).  The first is simple, but the second allows the var to be defined based on the txfee which is static in the case of basic, but deluxe now uses dynamically created txfees. Both of these vars have the same aim..to define a minimum required net profit. My assumption is that we dont need to define the net profit in relation to the txfee and we can move to defining it with profit_req_per_transaction.

min_output_size was a user request feature that was integrated into deluxe. There is no reason why this var couldnt be used and applied in all yield generator cases, but the code would need to be sure to use it in all cases.

The latest code i wrote has a profit_req_per_btc option which sets a net profit required based on the order size. For absorders is uses the maxsize and for relorders is checks the minsize and maxsize in relation to the relative cjfee. This could be offered to users as well. Do we want to give users additional useful options such as this?

The deluxe code currently uses offer_low/offer_high to let the user define the the lowest and highest offer size they want to be offered. If they are set to None, it will use the min_output_size and max_mixdepth_size respectively. This is another option that makes sense to be applied for all yield generator configurations. 

A bigger challenge is just going to be delivering the change to having the yg config in joinmarket.cfg in a way that is easy for users to migrate over from what they are used to. I am open to comments and suggestion on how to proceed.

**Comment by adlai** [comment]
@raedah why did you close this?

I think it's good to discuss this issue, although I've not got specific comments yet.

**Comment by raedah** [comment]
I wrote the code and included it in yg-oscillator,
https://github.com/JoinMarket-Org/joinmarket/blob/develop/yield-generator-oscillator.py#L80-L90

**Comment by adlai** [comment]
I'll leave this closed, but drop a [breadcrumb](https://pypi.python.org/pypi/ConfigArgParse) for any curious archæologists.
