### ISSUE TITLE
Yield generator crashing

### ISSUE THREAD

**Issue by NicolasDorier** [JoinMarket-Org/joinmarket#425]
How can I fix that, I just can let run my yield generator, it crashes after every transaction.
```
  File "yield-generator-deluxe.py", line 586, in main
    irc.run()
  File "C:\Users\Administrator\Desktop\JoinMarket\joinmarket-0.1.2\joinmarket\ir
c.py", line 639, in run
    self.__handle_line(line)
  File "C:\Users\Administrator\Desktop\JoinMarket\joinmarket-0.1.2\joinmarket\ir
c.py", line 522, in __handle_line
    self.__handle_privmsg(_chunks[0], _chunks[2], get_irc_text(line))
  File "C:\Users\Administrator\Desktop\JoinMarket\joinmarket-0.1.2\joinmarket\ir
c.py", line 473, in __handle_privmsg
    self.__on_privmsg(nick, parsed)
  File "C:\Users\Administrator\Desktop\JoinMarket\joinmarket-0.1.2\joinmarket\ir
c.py", line 351, in __on_privmsg
    self.on_order_fill(nick, oid, amount, taker_pk)
  File "C:\Users\Administrator\Desktop\JoinMarket\joinmarket-0.1.2\joinmarket\ma
ker.py", line 238, in on_order_fill
    taker_pubkey)
  File "C:\Users\Administrator\Desktop\JoinMarket\joinmarket-0.1.2\joinmarket\ma
ker.py", line 65, in __init__
    sys.exit(0)
```

Using bitcoind, and coinmarket 0.1.2

**Comment by chris-belcher** [comment]
By "after every transaction", do you mean it creates one coinjoin perfectly fine but then the second coinjoin it crashes?

If so, check that you've configured -walletnotify correctly.

Otherwise, could you upload your log file to pastebin.

**Comment by NicolasDorier** [comment]
@chris-belcher yes, I think so, I can't say for sure as I'm not in front of my computer when it crashes.

But indeed, I have not configured walletnotify as explained on: 
https://github.com/JoinMarket-Org/joinmarket/wiki/Running-JoinMarket-with-Bitcoin-Core-full-node

I thought I was too smart to have to read the fucking manunal, I'll reopen if I still have the problem after having configured that.

**Comment by NicolasDorier** [comment]
@chris-belcher I did not configure walletnotify, so maybe it was the problem, however the crash happened way after the coinjoin transaction (which succeeded) http://pastebin.com/Fmy6bKaY

**Comment by NicolasDorier** [comment]
Oh I noticed http://pastebin.com/GcBcztuD by scrolling up.... strange the stacktrace does not correspond though.

**Comment by AdamISZ** [comment]
@NicolasDorier the log is in the logs/ directory (will have a random_name.log name by default). (No need to publicize, of course, since it has private utxo data).

But indeed, if you did not configure walletnotify, this is exactly what will happen: after one tx, future txs can/will crash on the 'already used utxo' error, which is what you got.

**Comment by NicolasDorier** [comment]
Thanks a lot ! I'll reopen if any problem, but I'm confident this was indeed the problem.

**Comment by AdamISZ** [comment]
We could add a "please check you configured walletnotify correctly, see (link)" error message there. Pain figuring it out otherwise.

**Comment by NicolasDorier** [comment]
Ah and for information I'm running it on a windows server 2012. Had to install lots of dependencies to get everything to work, but it works. (I think you only tested on windows 10)

**Comment by AdamISZ** [comment]
Originally I figured out how to set it up for Win 7, we later discovered it works for 10. It is indeed quite a pain :) I put together a GUI that runs on Windows, but only for sendpayment so far. For yigen it's much better running from source.

If you have anything to add to the Wiki to help people setting up on win server 2012 (or other) please do, much appreciated.

**Comment by NicolasDorier** [comment]
Just did: https://github.com/JoinMarket-Org/joinmarket/wiki/Installing-JoinMarket-on-Windows-7-10-(temporary)

Good guide, the only missing thing was the cURL dependency which needed yet another redistributable.

**Comment by NicolasDorier** [comment]
Just to confirm: the problem was walletnotify indeed. I don't crash anymore thanks !

**Comment by AdamISZ** [comment]
@NicolasDorier I forgot to say, thanks for the curl add-in on the wiki. I guess this should be closed.

**Comment by raedah** [comment]
"the problem was walletnotify indeed"  could an error msg be improved here to let the user know this is the issue? Looks like they were just getting, maker.py", line 65, in __init__  sys.exit(0)

**Comment by chris-belcher** [comment]
@raedah I'm not sure there's a way for JoinMarket to tell how Bitcoin Core is configured. It would be nice if that was possible and then JM could warn the user.
