### ISSUE TITLE
Choosing the throttle parameters

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#447]
The throttle parameters are very conservative now, so much so that takers are having to raise their timeout values for maker's replying because the maker's have throttled themselves so much.

I read some of the xchat source but it uses a different algorithm to us and isn't very helpful. It uses a value of 120 bytes per second if I've understood right. https://github.com/hexchat/hexchat/blob/94a7fbae025b4a42f781e22a1e0d06a98f214888/src/common/server.c#L159

I think the best way to find out is empirical, try lots of different values and see what results in being kicked from flood.

**Comment by adlai** [comment]
Cross-pollinating with #446

**Comment by AdamISZ** [comment]
Copying my comment from IRC:

    <waxwing> belcher_: it's just very floody. we have a quadratic dependence on number of counterparties. total !tx output is something vaguely like (N-1) *(250*N*2+1) 
    <waxwing> sorry i meant (N-1)*(250*N*2), no +1 there
    <waxwing> the 2 is the estimate of how many utxos per counterparty (so that's lowballing) and the 250 is an estimate of how many b64 bytes per input utxo (and adding some for output too). 300 might be better actually.
    <waxwing> anyway so my point is just, for more than say 5 counterparties it's many kilobytes of data, IRC is just not intended for that use.

Testing to optimise: yes, it's possible it could be better, I tried to test in a number of ways, but it was really hard to get realistic testing (see my comment here https://github.com/JoinMarket-Org/joinmarket/issues/426#issuecomment-184253675). I think there probably isn't that much wriggle room (~3 times faster than xchat client is working OK; if we can get it up to 6 times faster, I'd be surprised, but maybe).

But this feels like an area with limited/incremental win (and also brittle; server specific) given the quadratic aspect mentioned.

A larger maker_timeout_sec is in my opinion a reasonable thing to do today, mainly just to avoid newbs having failures they don't understand, although of course it's a tradeoff. While the more meaningful solution will be to find a more accommodating messaging layer, in one form or another.

Oh and PS: there is another win to be had by not base64 encoding the transaction before encryption (we currently do 2 base64 encodings, which is dumb and adds 33% overhead).

**Comment by AdamISZ** [comment]
> The throttle parameters are very conservative now, so much so that takers are having to raise their timeout values for maker's replying because the maker's have throttled themselves so much.

Minor point, but it's the taker that's throttling its sends (sending all the !tx messages broadcast), pretty sure that's the only bottleneck point.

**Comment by chris-belcher** [comment]
Linking this https://github.com/JoinMarket-Org/joinmarket/commit/4c08910870257bd1718bfb3e4a2887fd79fb8364

**Comment by AdamISZ** [comment]
We ended up sticking with the parameters mentioned in the commit from the above comment. Probably nothing else to be done here. Closing.
