### ISSUE TITLE
Money isn't show up

### ISSUE THREAD

**Issue by yosims88** [JoinMarket-Org/joinmarket#459]
Not sure if this is where I'd go, but I'm out of options. I've sent 1 BTC to an address generated. Blockchain shows 25+ confirmations, resync and my joinmarket shows 0. I sent another 0.84 cents, same thing. 

Am I ever going to see my money? 
![wtf1](https://cloud.githubusercontent.com/assets/17777435/13694256/66292894-e708-11e5-9ccf-ee0fa623d082.png)

**Comment by AdamISZ** [comment]
The status bar says "reading wallet from blockchain.." It appears there's something stopping you syncing properly. The first thing I would do is restart the program and load the wallet again. What is your blockchain interface (first entry in the settings tab)? If it's the default, blockr, then you can check that you can reach the website blockr.io. If the problem persists, you might need to give more details about the situation. Don't worry, the coins will be accessible.
