### ISSUE TITLE
patientsendpayment.py crashes: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by domob1812** [JoinMarket-Org/joinmarket#462]
Running `patientsendpayment.py` of the current `master` branch consistently crashes for me after some time (presumably when someone tries to take the offer).  I'm using this exact command to run it:

    python patientsendpayment.py -f 0 -w 24 -c 0 -N 2 -m 3 wallet.json 80000000 someaddress

It fails with this error:

    Traceback (most recent call last):
      File "patientsendpayment.py", line 237, in main
        irc.run()
      File "/home/daniel/Projekte/joinmarket/joinmarket/irc.py", line 639, in run
        self.__handle_line(line)
      File "/home/daniel/Projekte/joinmarket/joinmarket/irc.py", line 522, in __handle_line
        self.__handle_privmsg(_chunks[0], _chunks[2], get_irc_text(line))
      File "/home/daniel/Projekte/joinmarket/joinmarket/irc.py", line 473, in __handle_privmsg
        self.__on_privmsg(nick, parsed)
      File "/home/daniel/Projekte/joinmarket/joinmarket/irc.py", line 359, in __on_privmsg
        self.on_seen_auth(nick, i_utxo_pubkey, btc_sig)
      File "/home/daniel/Projekte/joinmarket/joinmarket/maker.py", line 245, in on_seen_auth
        self.active_orders[nick].auth_counterparty(nick, pubkey, sig)
      File "/home/daniel/Projekte/joinmarket/joinmarket/maker.py", line 88, in auth_counterparty
        btc_pub = btc.privtopub(btc_key)
      File "/home/daniel/Projekte/joinmarket/bitcoin/main.py", line 327, in privkey_to_pubkey
        f = get_privkey_format(privkey)
      File "/home/daniel/Projekte/joinmarket/bitcoin/main.py", line 238, in get_privkey_format
        elif len(priv) == 32: return 'bin'
    TypeError: object of type 'NoneType' has no len()

I can also send the full log file privately on request.

**Comment by chris-belcher** [comment]
Unfortunately patientsendpayment.py can't work without a protocol update. It can only send to addresses you already know the privkey for.

In the protocol, makers send the coinjoin address pubkey and sign a message with the private key to authenticate the encryption and stop mitm attacks.

We should probably write this somewhere in the script or wiki so users don't waste their time..

**Comment by domob1812** [comment]
Ah ok, so that then means that it is simply not possible to do this?  In my particular case, I actually know the privkey (as the address is my own, just in a different wallet).  Is it possible to use `patentsendpayment.py` somehow to do that, or should I simply give up on the script at all?

**Comment by chris-belcher** [comment]
Ah, in that case it is possible. You'd need to import the private key into JoinMarket's internal wallet using wallet-tool.py

JoinMarket only supports compressed keys, so if you're other wallet uses uncompressed keys then it wont work.

**Comment by domob1812** [comment]
Great, that worked!  So I assume that this bug can be closed.  Instead, it would be nice to change `patientsendpayment.py` in the following way:  It should automatically request the needed privkey so that this works without importing it first (or, at least, give an explicit error message).  This doesn't require a protocol change, and it is at least useful to extract liquidity from a JoinMarket wallet without paying for tx fees (and with the benefit of improving market depth).  That's what I'm using it for.

**Comment by chris-belcher** [comment]
It's planned to update the protocol soonish to make patientsendpayment work for its intended use. Maybe until then it can have a message printed out when people try to use it.

**Comment by chris-belcher** [comment]
https://github.com/JoinMarket-Org/joinmarket/commit/b9a673b2b6918de24d9d7420b7a2c9a202c9f878
