### ISSUE TITLE
oscillator sometimes creates double entries in the csv file

### ISSUE THREAD

**Issue by raedah** [JoinMarket-Org/joinmarket#466]
Oscillator puts a transaction entry in the csv file at first when the tx is unconfirmed, and then updates the row once the transaction is confirmed.  For an unknown reason, the unconfirmed tx is sometimes not getting removed, and a double entry is being created. This does not happen all the time. This does not cause any big problems, but is annoying. 

The tx's will have identical timestamps, amounts, and earnings, but the confirmation_time field will be zero on the unconfirmed tx row.

The code for this is here: https://github.com/JoinMarket-Org/joinmarket/blob/develop/yield-generator-oscillator.py#L607-L639

**Comment by AdamISZ** [comment]
No longer relevant as of 0.2.* (although status of custom ygs is up for debate, has been discussed elsewhere).
