### ISSUE TITLE
Create tests for pybitcointools transaction deserializing routines

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#468]
We all know pybitcointools is a bit rubbish #61 and in hindsight we never should of used it. But it's not easy to move away and we've already engulfed that library to a large extent.

At some point we'll move to using libsecp256k1 instead of Vitalik's pure python ECC routines. We already have a testing suite for the BIP32 code.
The only notable part left that we use is the transaction deserializing routines. They are quite important, if they have bugs then makers could be tricked into signing transactions that they don't intend to sign.

Therefore we should write tests for those routines. Tagged as medium difficulty because even though the tests are easy to write, coming up with good tests is not obvious.

**Comment by AdamISZ** [comment]
I was thinking about this (idly) last week and started wondering if there are test suites in Bitcoin itself which we could reuse. I agree it's a non-trivial exercise to come up with good test cases.

**Comment by AdamISZ** [comment]
This has been addressed by #476 #477 #482 #490.

More can be done of course. But close if you like.

**Comment by AdamISZ** [comment]
Closing, we're long past the pybitcointools ECC routines now, and we have deserialization tests although we could have better ones for sure.
