### ISSUE TITLE
Suggestion for redesign of patientsendpayment

### ISSUE THREAD

**Issue by domob1812** [JoinMarket-Org/joinmarket#480]
I think that `patientsendpayment` is not 100% useful for the stated purpose, but could very well be slightly repurposed to become more useful.  In particular, the current behaviour is this:

It creates a maker and sends possibly many payments with value zero up to the tx amount to the recipient address.  After the waittime is reached, it sends the remaining amount as a taker.

This is intended to let people send payments using JoinMarket as a maker if they are willing to wait a certain time.  I think, however, that this has two problems:  First, it may send many small transactions adding up to the final amount to the recipient address; this is probably not what you want if you want to do a transaction, and it reuses the recipient address.  Second, unless you are lucky enough to find takers that add up exactly to your transaction amount, you will be left with a remaining balance at the end of the waittime and thus have to send a taker transaction anyway; thus, you could have sent it already to begin with.

Nevertheless, I have been using `patientsendpayment` myself some times already, and think that there is a slightly different purpose where it could be a perfect fit:  Reshuffling coins between my own wallets (including between my yieldgenerator and Bitcoin Core wallet).  In these situations, there is time enough to wait for a taker, and the actual amount transferred does not matter too much - I'm fine with, say, anything between 0.1 and 0.5 BTC, as I can start another tx later if I want and need it.  Also, it is nice to have "zero fee" inter-wallet transfers, while providing JoinMarket liquidity at the same time and, finally, doing a little to protect my own privacy.

For this purpose, a slightly modified `patientsendpayment` (with added minimum order amount and exiting after a given number of transactions) works reasonably well.  It would be even better, though, to change it in the following ways:
- Change the transaction amount to a [min, max] interval on the command line.
- Remove the waittime logic and instead exit after the first (or a given number) of transactions.
- Ask for the recipient privkey, import it temporarily into the wallet, and remove it from there after the send is done.  (Or just keep it around in memory and use it from there to satisfy the JoinMarket protocol.)

IMHO, these changes would make `patientsendpayment` much more useful.  What do you think?  Alternatively, if you believe that `patientsendpayment` works well for the originally intended purpose despite my own doubts, this could be done as a new tool.  I'm willing to spend time on that as long as there is agreement on what we should actually build.

**Comment by chris-belcher** [comment]
You can write it if you like it, although I always considered `patientsendpayment` to be broken until the protocol is updated.

**Comment by chris-belcher** [comment]
#687 is a pull request that implements (some of) these suggestions. The address re-use problem is something I probably only realised by reading this thread, which is fixed now.
