### ISSUE TITLE
Show exact amount of coins going to specific addresses for tumbler.py

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#483]
Is there any reason for not showing the exact bitcoin amounts before the tumbler starts, only the amount_fraction?

**Comment by chris-belcher** [comment]
We can't know in advance with the way it's coded right now because it's not possible to predict the all fees.

In #169 I had some ideas about having all-but-one of the addresses have an amount associated with it and the rest of the coins getting sent to the last address.

**Comment by AdamISZ** [comment]
In the absence of a concrete suggestion (other than #169 which exists), closing.
