### ISSUE TITLE
Towards new release 0.1.4

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#495]
I think we should tag a new release that collects up all the bug fixes and new features made over the last 2 or 3 months.

I still sometimes get PMs about crash or bug in JoinMarket that was fixed in the develop branch months ago.

#494 was the last major feature I wanted to add for this release. When this timeout code gets merged then #56 could be quickly implemented.

After that 3 or 4 of some of the Easy / Quick issues could be written. Then we feature freeze and ask people to try out develop.

If someone else wants to have a new feature included in this release let us know.

**Comment by AdamISZ** [comment]
I certainly understand why #494 is something you want to add before the release. But do we need anything else? I'd like there to be a release ASAP. One reason is: I want to rebuild the GUI with the updates, and also add private key export to it.

**Comment by chris-belcher** [comment]
No reason really, we can skip them to speed up release.

**Comment by raedah** [comment]
It would be nice to see https://github.com/JoinMarket-Org/joinmarket/issues/466 fixed. It is partially related to how on_tx_unconfirmed is being called by on_tx_confirmed. I am stumped on it, but perhaps some other eyes could easily find the issue.

**Comment by chris-belcher** [comment]
@raedah have you tried the wallet-history feature from #484 ? It's an alternative way from looking at the csv file.
I know it doesn't fix that bug but at least you know there's another way to get information that should be more accurate because it reads almost directly from the blockchain.

**Comment by chris-belcher** [comment]
We should also merge #408 before releasing too.

**Comment by chris-belcher** [comment]
Should it be 0.1.4 or 0.2.0 ?

**Comment by AdamISZ** [comment]
Well, the 0.2.0 thread talked about scalability and anti-sybil and protocol updates for that as a target. But we don't seem to be very near that. Of course, we don't have to stick to that.

**Comment by chris-belcher** [comment]
Some final merges 

#502 can be merged quite soon
#408 too
#455 could be finished or maybe left for later
#439 fixes a rare crash to do with database concurrency

Then we can post on forums asking people to try develop as a release candidate.

**Comment by AdamISZ** [comment]
I don't know what was wrong with making a release a couple of weeks ago around when this post was made? There were a lot of significant changes already between master and develop at that point. I actually wanted to have the release a week or two before that.

You're suggesting more fixes that could easily push it back another couple of weeks. Our last release was in mid Feb. Although it's not the time as much as the volume of changes that matters to me. My "selfish" reason above is just a small aspect, also the many useful changes like throttling improvements, several bugfixes, and especially libsecp256k1 support are still not "public".

**Comment by chris-belcher** [comment]
I'm sorry I didn't realise you wanted a release so soon. I can do it very soon.

**Comment by chris-belcher** [comment]
released now
