### ISSUE TITLE
Is it ok to send coins intot a wallet which is being used by a tumbler?

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#497]
For example, tumbler.py wallet.json is running, what happens if I send coins to one of wallet.json's addresses?

**Comment by chris-belcher** [comment]
It probably won't detect them because sync_unspent() which updates all the coins in your wallet only runs once at the start.

**Comment by chris-belcher** [comment]
BTW recently I added sync_unspent() to the beginning of create_tx() in tumbler
https://github.com/JoinMarket-Org/joinmarket/commit/04c277ede58e9f397c5cd7238d707f3cf61f7511

So in develop you can add coins now to tumbler as it's running, and it's much less likely to get out of sync in a weird way.

**Comment by dreboli** [comment]
Does this mean the newly added coins will be tumbled too?
What happens when the tumbler already tumbled coins into depth 2, and I add coins to depth 0?

**Comment by chris-belcher** [comment]
Newly added coins will only be tumbled if the tumbler run hasn't gotten to them yet.

So if you want to add new coins to a run and tumbler is currently at transaction 1 in mixdepth 0, you have to send the coins to mixdepth 1 or above.
