### ISSUE TITLE
Move some files to test/ to declutter the joinmarket root directory

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#510]
./setup.cfg
./joinmarket.cfg
./requirements-dev.txt
./miniircd/

And so on, could be moved inside the test/ directory so the root folder seems less cluttered. Maybe ./htmlcov/ could be made to be created inside test/ too.

**Comment by AdamISZ** [comment]
Sorry I never got round to answering this, but I think setup.cfg and requirements* might have to stay top level. miniircd makes sense to go in test/ , agreed. Not sure why joinmarket.cfg would go into test/ though?

I think this naturally fits in with work to make the main joinmarket directory a package (like https://github.com/AdamISZ/joinmarket_core type of thing, although maybe just called joinmarket, and I don't know if it should be a separate repo or not, see comments in #549 ).

**Comment by chris-belcher** [comment]
No idea what I meant. Maybe /test/regtest_joinmarket.cfg but thats already in test/

**Comment by AdamISZ** [comment]
I think the rationalisation done so far in 0.2.* is already mostly enough; `miniircd` directory removed (git submodule is a pain, no need for it), `libnacl` is also removed. setup.cfg and requirements*.txt must stay I think. So, closing.
