### ISSUE TITLE
Optional use of secp256k1 in the develop branch; testing appreciated

### ISSUE THREAD

**Issue by HamishMacEwan** [JoinMarket-Org/joinmarket#528]
Hi,

Here are full logs of two install attempts.  Per your suggestion at:

https://www.reddit.com/r/joinmarket/comments/4cwjk9/optional_use_of_secp256k1_in_the_develop_branch/d3777ey

I checked earlier in the log (first upload below) and found setuptools out of date:
[secp256k1Install.txt](https://github.com/JoinMarket-Org/joinmarket/files/266997/secp256k1Install.txt)

Fixed that but creating still not happy, short message: "Failed building wheel for secp256k1"

[secp256k1Install2.txt](https://github.com/JoinMarket-Org/joinmarket/files/266996/secp256k1Install2.txt)

Thanks for all the help.

**Comment by raedah** [comment]
install1 says, 
   Installed /tmp/easy_install-mLEUH5/pytest-runner-2.6.2/setuptools_scm-1.11.0-py2.7.egg
    your setuptools is too old (<12)

**Comment by HamishMacEwan** [comment]
And so I updated setuptools following the instructions here:

http://askubuntu.com/questions/683601/how-to-upgrade-python-setuptools-12-2-on-ubuntu-15-04
[Though I'm using 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux]

The 2nd log has a different error and I can't see any complaint there about setuptools.

**Comment by raedah** [comment]
honestly this looks like problems with compilation. you should ask the support channel for ubuntu what is wrong with your compiler setup.

**Comment by HamishMacEwan** [comment]
OK, well I installed from here:
https://github.com/bitcoin-core/secp256k1

and it must have put things in the right place because 

sudo pip install secp256k1

Ran to completion without errors and a test of:

python wallet-tool.py wallet.json history

Ran significantly quicker and presumably all the other goodness this binding/library offers happened too.

**Comment by AdamISZ** [comment]
@HamishMacEwan I see. It looks like: the automated "under the hood" build done by secp256k1-py failed to work in your case, so you had to build libsecp256k1 separately.

I'm not sure what to make of that, but thanks for the report.
