### ISSUE TITLE
JSON RPC connection failed

### ISSUE THREAD

**Issue by jamesphillipturpin** [JoinMarket-Org/joinmarket#533]
I'm trying to get JoinMarket to work with Bitcoin Core now. This is the error I get:
![json-rpc connection failed](https://cloud.githubusercontent.com/assets/4017015/15457752/4205342e-2044-11e6-9dbf-bd2afd143666.png)

I don't know whether the problem is related to running Bitcoin Core on a USB drive, or something else entirely. Either way I'm a bit lost on how the configuration files work - I'm just trying to follow the directions. I put the Bitcoin.cfg file in the same directory as Bitcoin Core, "F:\Bitcoin". I put the joinmarket.cfg file and all the python scipts in "C:\Python27".

I'll paste the .cfg file contents below as separate messages for clarity and to avoid a bunch of attachments.

**Comment by jamesphillipturpin** [comment]
# bitcoin.conf configuration file. Lines beginning with # are comments.
 
 
 # Network-related settings:
 
 # Run on the test network instead of the real bitcoin network.
testnet=0
 
 # Connect via a socks4 proxy
proxy=127.0.0.1:9050
 
 ##############################################################
 ##            Quick Primer on addnode vs connect            ##
 ##  Let's say for instance you use addnode=4.2.2.4          ##
 ##  addnode will connect you to and tell you about the      ##
 ##    nodes connected to 4.2.2.4.  In addition it will tell ##
 ##    the other nodes connected to it that you exist so     ##
 ##    they can connect to you.                              ##
 ##  connect will not do the above when you 'connect' to it. ##
 ##    It will *only* connect you to 4.2.2.4 and no one else.##
 ##                                                          ##
 ##  So if you're behind a firewall, or have other problems  ##
 ##  finding nodes, add some using 'addnode'.                ##
 ##                                                          ##
 ##  If you want to stay private, use 'connect' to only      ##
 ##  connect to "trusted" nodes.                             ##
 ##                                                          ##
 ##  If you run multiple nodes on a LAN, there's no need for ##
 ##  all of them to open lots of connections.  Instead       ##
 ##  'connect' them all to one node that is port forwarded   ##
 ##  and has lots of connections.                            ##
 ##       Thanks goes to [Noodle] on Freenode.               ##
 ##############################################################
 
 # Use as many addnode= settings as you like to connect to specific peers
addnode=69.164.218.197
addnode=10.0.0.2:8333
 
 # ... or use as many connect= settings as you like to connect ONLY
 # to specific peers:
connect=69.164.218.197
connect=10.0.0.1:8333
 
 
 # Maximum number of inbound+outbound connections.
maxconnections=
 
 
 # JSON-RPC options (for controlling a running Bitcoin/bitcoind process)
 
 # server=1 tells Bitcoin-QT to accept JSON-RPC commands.
server=1
 
 # You must set rpcuser and rpcpassword to secure the JSON-RPC api
rpc_user = MJ0A5lYx
rpc_password = w6Xi6TgQh46v00B1bjJwTPNl0BLTanRGWlhKvo3Of6tLB8sZZZizFAmM8ufunjmV

# Joinmarket
walletnotify=curl -sI --connect-timeout 1 http://localhost:62602/walletnotify?%s
alertnotify=curl -sI --connect-timeout 1 http://localhost:62602/alertnotify?%s 
 # How many seconds bitcoin will wait for a complete RPC HTTP request.
 # after the HTTP connection is established. 
rpctimeout=30
 
 # By default, only RPC connections from localhost are allowed.  Specify
 # as many rpcallowip= settings as you like to allow connections from
 # other hosts. As of Bitcoin Core 0.10.0, wildcards are no longer allowed.  Use one of the sample forms below.
 # NOTE: opening up the RPC port to hosts outside your local
 # trusted network is NOT RECOMMENDED, because the rpcpassword
 # is transmitted over the network unencrypted.
rpcallowip=10.1.1.34
rpcallowip=192.168.1.0/255.255.255.0
rpcallowip=172.16.0.0/24
 
 # Listen for RPC connections on this TCP port:
rpcport=8332
 
 # You can use Bitcoin or bitcoind to send commands to Bitcoin/bitcoind
 # running on another host using this option:
rpcconnect=127.0.0.1
 
 # Use Secure Sockets Layer (also known as TLS or HTTPS) to communicate
 # with Bitcoin -server or bitcoind
rpcssl=1
 
 # OpenSSL settings used when rpcssl=1
rpcsslciphers=TLSv1+HIGH:!SSLv2:!aNULL:!eNULL:!AH:!3DES:@STRENGTH
rpcsslcertificatechainfile=server.cert
rpcsslprivatekeyfile=server.pem
 
 
 # Miscellaneous options
 
 # Set gen=1 to attempt to generate bitcoins
gen=0
  
 # Pre-generate this many public/private key pairs, so wallet backups will be valid for
 # both prior transactions and several dozen future transactions.
keypool=100
 
 # Pay an optional transaction fee every time you send bitcoins.  Transactions with fees
 # are more likely than free transactions to be included in generated blocks, so may
 # be validated sooner.
paytxfee=0.00
 
 # Allow direct connections for the 'pay via IP address' feature.
allowreceivebyip=1
   
 # User interface options
 
 # Start Bitcoin minimized
min=1
 
 # Minimize to the system tray
minimizetotray=1

**Comment by jamesphillipturpin** [comment]
[BLOCKCHAIN]
blockchain_source =  bitcoin-rpc
#options: blockr, bitcoin-rpc, json-rpc, regtest
# for instructions on bitcoin-rpc read
# https://github.com/chris-belcher/joinmarket/wiki/Running-JoinMarket-with-Bitcoin-Core-full-node
network = mainnet
rpc_host = localhost
rpc_port = 8332
rpc_user = MJ0A5lYx
rpc_password = w6Xi6TgQh46v00B1bjJwTPNl0BLTanRGWlhKvo3Of6tLB8sZZZizFAmM8ufunjmV

# Joinmarket
walletnotify=curl -sI --connect-timeout 1 http://localhost:62602/walletnotify?%s
alertnotify=curl -sI --connect-timeout 1 http://localhost:62602/alertnotify?%s

[MESSAGING]
host = irc.cyberguerrilla.org
channel = joinmarket-pit
port = 6697
usessl = true
socks5 = false
socks5_host = localhost
socks5_port = 9050
#for tor
#host = 6dvj6v5imhny3anf.onion
#port = 6697
#usessl = true
#socks5 = true
maker_timeout_sec = 30

[POLICY]
# for dust sweeping, try merge_algorithm = gradual
# for more rapid dust sweeping, try merge_algorithm = greedy
# for most rapid dust sweeping, try merge_algorithm = greediest
# but don't forget to bump your miner fees!
merge_algorithm = default
# the fee estimate is based on a projection of how many satoshis
# per kB are needed to get in one of the next N blocks, N set here
# as the value of 'tx_fees'. This estimate is high if you set N=1, 
# so we choose N=3 for a more reasonable figure,
# as our default. Note that for clients not using a local blockchain
# instance, we retrieve an estimate from the API at blockcypher.com, currently.
tx_fees = 3
# the range of confirmations passed to the `listunspent` bitcoind RPC call
# 1st value is the inclusive minimum, defaults to one confirmation
# 2nd value is the exclusive maximum, defaults to most-positive-bignum (Google Me!)
# leaving it unset or empty defers to bitcoind's default values, ie [1, 9999999]
#listunspent_args = []
# that's what you should do, unless you have a specific reason, eg:
#  !!! WARNING !!! CONFIGURING THIS WHILE TAKING LIQUIDITY FROM
#  !!! WARNING !!! THE PUBLIC ORDERBOOK LEAKS YOUR INPUT MERGES
#  spend from unconfirmed transactions:  listunspent_args = [0]
# display only unconfirmed transactions: listunspent_args = [0, 1]
# defend against small reorganizations:  listunspent_args = [3]
#   who is at risk of reorganization?:   listunspent_args = [0, 2]
# NB: using 0 for the 1st value with scripts other than wallet-tool could cause
# spends from unconfirmed inputs, which may then get malleated or double-spent!
# other counterparties are likely to reject unconfirmed inputs... don't do it.

**Comment by jamesphillipturpin** [comment]
LOL, github interpreted the punctuation in the .cfg files as font formatting, sorry about that.  I'm not shouting.

The rpc-username and rpc-password are just randomly generated strings, unrelated to any past or future passwords, that I will change on my next iteration. I've shut down Bitcoin Core and JoinMarket for now. Don't worry, I can't be hacked from posting that.

**Comment by AdamISZ** [comment]
I edited (put ``` above and below) to format them.

**Comment by chris-belcher** [comment]
Does bitcoin.conf actually get read by Bitcoin Core?

Try putting only connect=0.0.0.0 and checking that it indeed fails to connect to anything.

**Comment by jamesphillipturpin** [comment]
Even with connect=0.0.0.0 as the only thing in the bitcoin.conf file it still synchronizes with the network, so Bitcoin Core note reading it would seem to be the problem.
I saved it with quotes as "bitcoin.conf" from Notepad, with the quotes and file managers see it as a CONF file type. I don't know if that is really the correct filename or how to tell Bitcoin Core to read it, but it's not bitcoin.conf.txt anyway.

**Comment by Lonestaz** [comment]
There's no quotes on bitcoin.conf filename. It should be called just
bitcoin.conf Also, make sure it's in the data directory where the
blockchain is downloaded. Only folder bitcoin core reads from.

Even with connect=0.0.0.0 as the only thing in the bitcoin.conf file it
still synchronizes with the network, so Bitcoin Core note reading it would
seem to be the problem.
I saved it with quotes as "bitcoin.conf" from Notepad, with the quotes and
file managers see it as a CONF file type. I don't know if that is really
the correct filename or how to tell Bitcoin Core to read it, but it's not
bitcoin.conf.txt anyway.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/JoinMarket-Org/joinmarket/issues/533#issuecomment-221044869>

**Comment by jamesphillipturpin** [comment]
The quotes are just the override for the default extensions in Notepad (or a number of other editors used in Windows). Otherwise it would be bitcoin.conf.txt. Apparently Microsoft doesn't like to give users easy access to edit file extensions. 

I misunderstood which directory. After some searching I found this page which describes how to find the data directory:
https://en.bitcoin.it/wiki/Data_directory#Windows
That seems to fix the problem of not reading the bitcoin.conf file anyway. Hopefully I can debug the rest myself.

Thanks for your help!

**Comment by jamesphillipturpin** [comment]
![ssl mode for rpc -rpcssl is no longer supported](https://cloud.githubusercontent.com/assets/4017015/15485081/2130d48e-20f2-11e6-9344-8b4806d0cb55.png)
I'm not sure what this means. Lol. Am I using features and settings in the configuration file that are no longer supported with the current version of Bitcoin Core? If so, are there updated instructions? Or am I just missing something basic again?

**Comment by jamesphillipturpin** [comment]
There is some discussion of this -rpcssl no longer being supported here:
https://bitcoincore.org/en/releases/0.12.0/
I would imagine I'm not the first person to run into this.

**Comment by Lonestaz** [comment]
I'm running Bitcoin Core version v0.12.1 (64-bit) on windows 10 with the yield generator. Should work in other versions of Bitcoin Core and Windows.

**This basically all you need in bitcoin.conf: The username and password should be your own**
 ```
# server=1 tells Bitcoin-QT to accept JSON-RPC commands.
 server=1
 
 # You must set rpcuser and rpcpassword to secure the JSON-RPC api
 rpcuser=abc
 rpcpassword=abc
 
 # How many seconds bitcoin will wait for a complete RPC HTTP request.
 # after the HTTP connection is established. 
 rpctimeout=30
 
 # Listen for RPC connections on this TCP port:
 rpcport=8332
 
 # You can use Bitcoin or bitcoind to send commands to Bitcoin/bitcoind
 # running on another host using this option:
 rpcconnect=127.0.0.1
 
 #walletnotify options for joinmarket
 walletnotify=curl -sI --connect-timeout 1 http://localhost:62602/walletnotify?%s
 alertnotify=curl -sI --connect-timeout 1 http://localhost:62602/alertnotify?%s
```


**This should be in the standard joinmarket cfg at the beginning. The rest of the config you can pretty much leave untouched. Make sure the username and password match in bitcoin.conf**

```
[BLOCKCHAIN]
blockchain_source = bitcoin-rpc
network = mainnet
rpc_host = localhost
rpc_port = 8332
rpc_user = abc
rpc_password = abc

[MESSAGING]
host = irc.cyberguerrilla.org
channel = joinmarket-pit
port = 6697
usessl = true
socks5 = false
socks5_host = localhost
socks5_port = 9050
#for tor
#host = 6dvj6v5imhny3anf.onion
#port = 6697
#usessl = true
#socks5 = true

[TIMEOUT]
maker_timeout_sec = 30
unconfirm_timeout_sec = 90
confirm_timeout_hours = 6

[POLICY]
# for dust sweeping, try merge_algorithm = gradual
# for more rapid dust sweeping, try merge_algorithm = greedy
# for most rapid dust sweeping, try merge_algorithm = greediest
# but don't forget to bump your miner fees!
merge_algorithm = default
# the fee estimate is based on a projection of how many satoshis
# per kB are needed to get in one of the next N blocks, N set here
# as the value of 'tx_fees'. This estimate is high if you set N=1, 
# so we choose N=3 for a more reasonable figure,
# as our default. Note that for clients not using a local blockchain
# instance, we retrieve an estimate from the API at blockcypher.com, currently.
tx_fees = 3
# the range of confirmations passed to the `listunspent` bitcoind RPC call
# 1st value is the inclusive minimum, defaults to one confirmation
# 2nd value is the exclusive maximum, defaults to most-positive-bignum (Google Me!)
# leaving it unset or empty defers to bitcoind's default values, ie [1, 9999999]
#listunspent_args = []
# that's what you should do, unless you have a specific reason, eg:
#  !!! WARNING !!! CONFIGURING THIS WHILE TAKING LIQUIDITY FROM
#  !!! WARNING !!! THE PUBLIC ORDERBOOK LEAKS YOUR INPUT MERGES
#  spend from unconfirmed transactions:  listunspent_args = [0]
# display only unconfirmed transactions: listunspent_args = [0, 1]
# defend against small reorganizations:  listunspent_args = [3]
#   who is at risk of reorganization?:   listunspent_args = [0, 2]
# NB: using 0 for the 1st value with scripts other than wallet-tool could cause
# spends from unconfirmed inputs, which may then get malleated or double-spent!
# other counterparties are likely to reject unconfirmed inputs... don't do it.

tx_broadcast = self
#options: self, random-peer, not-self, random-maker
# self = broadcast transaction with your own ip
# random-peer = everyone who took part in the coinjoin has a chance of broadcasting
# not-self = never broadcast with your own ip
# random-maker = every peer on joinmarket has a chance of broadcasting, including yourself
```

**Comment by jamesphillipturpin** [comment]
OK. It looks like that works, with Python reading the wallet, telling Bitcoin Core about receiving addresses to watch, and talking with network of other JoinMarket users. I don't quite know what was going wrong with my previous configuration files but that's OK as it works now. I consider this issue closed.
