### ISSUE TITLE
ValueError: need more than 2 values to unpack (on tumbler.py)

### ISSUE THREAD

**Issue by agnerio** [JoinMarket-Org/joinmarket#538]
I couldn't find an issue with this error, so here it is:

I'm running under Fedora 23 and ```bitcoin-rpc``` as ```blockchain_source```.
The last run of tumbler.py (called with all three addresses, so not related to another issue I saw around here) was taking about 5+ hours than estimated, I thought that was odd and finished the process. Then, I started the tumble.py with ```-m 2``` for the mixdepth the remaining coins were in.

It started creating some TXs, all seemed fine, then I saw this error and no more transactions. It's already 3+ hours more than estimated time:

```
2016-05-25 19:04:10,090 [Thread-9    ] [DEBUG]  orderlist = 

2016-05-25 19:04:10,091 [Thread-9    ] [DEBUG]  ERROR not enough liquidity in the orderbook
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 1076, in run
    self.function(*self.args, **self.kwargs)
  File "/home/user/Projects/joinmarket/joinmarket/blockchaininterface.py", line 420, in bitcoincore_timeout_callback
    timeoutfun(uc_called)
  File "tumbler.py", line 125, in timeout_callback
    self.create_tx()
  File "tumbler.py", line 242, in create_tx
    self.ignored_makers)
ValueError: need more than 2 values to unpack
```
I let tumbler.py running for some time after the exception and got just IRC logs.
Known issue or any thoughts on what else I could investigate to make this more helpful?
Could not reproduce it again, btw.

**Comment by dreboli** [comment]
Same here. [scrubbed log](https://share.riseup.net/#XpX5zdZJxgsCjUKga6bPpw)

**Comment by chris-belcher** [comment]
Thanks for the report

The error is in this line: https://github.com/JoinMarket-Org/joinmarket/blob/master/joinmarket/support.py#L363

It needs to return None, 0, 0
So three values not two, then it wont crash with that ValueError

**Comment by AdamISZ** [comment]
It's sad really, I already fixed that bug but I can't remember where :)

**Comment by chris-belcher** [comment]
lets see how this goes https://github.com/JoinMarket-Org/joinmarket/commit/8fa6b0acfd13913d8c9130f26575b1be8d6e97b7
