### ISSUE TITLE
sanity_check in yield-generator-oscillator.py rejects long integers, breaks with 22 bitcoin

### ISSUE THREAD

**Issue by jamesphillipturpin** [JoinMarket-Org/joinmarket#540]
So if offer['maxsize'] is 2147483647 or less it is type int but it is instead 2147483648 or more then it is type long. The sanity_check rejects anything other than type int. These are satoshis so it breaks with 22 bitcoin. So I'm not sure if I should modify the sanity check by changing this line:
`assert isinstance(offer['maxsize'], int)`
to:
`assert (isinstance(offer['maxsize'], int) or isinstance(offer['maxsize'], long))`

Or modify offers just before doing sanity check:
`for offer in offers:  if isinstance(offer['maxsize'],long): offer['maxsize'] =  2147483647`

I suppose I could even just comment out the sanity check. I'm just wondering if any of these options are expected to create problems? I've already run larger transactions through one of the other yield generators in a previous version, so although I could imagine type long numbers creating problems, that doesn't seem to be the case. I thought I should check in with the community before modifying code on the fly though.

**Comment by raedah** [comment]
It shouldn't be a problem for you to modify sanity_check for your needs. That code is straight forward and wont cause any other issues. Question though as to why this bug is still being caused for you. Other use it with amounts over 22 bitcoins and have had no issue, so this may be something specific to your platform architecture.

**Comment by jamesphillipturpin** [comment]
For my bot I've changed line 184 of joinmarket/yield-generator-oscillator.py to:
`        assert (isinstance(offer['maxsize'], int) or isinstance(offer['maxsize'], long))`

I don't know why my local installation of Python uses 32 bit for int when I have a 64 bit processor, other than that the documentation indicates that as the minimum spec.

More generally, this test code indicates that Python refuses to cast integers larger than a 32 bit signed int as int rather than long:
`>>> type(int(pow(2,31)-1))
<type 'int'>
>>> type(int(pow(2,31)))
<type 'long'>`
I've reinstalled Python 2.7.11 from a couple different sources, with no change to this behavior.

**Comment by jamesphillipturpin** [comment]
After making more changes to my personal offers I also had to change line 183 similarly.
So in total I changed lines 183 to 184 of joinmarket/yield-generator-oscillator.py to:

```
assert (isinstance(offer['minsize'], int) or isinstance(offer['minsize'], long))
assert (isinstance(offer['maxsize'], int) or isinstance(offer['maxsize'], long))
```

**Comment by raedah** [comment]
Okay, well still not sure exactly what causes the 'long' issue on the platform, but once you are sure this code does what you need, please submit a pull request for it. Looks like it would easily be compatible for all and save other who might encounter it.
