### ISSUE TITLE
Travis builds are not being triggered

### ISSUE THREAD

**Issue by AdamISZ** [JoinMarket-Org/joinmarket#557]
This seems rather important as by Murphy's law we are suddenly getting a ton of PRs (and have a number of important issues to address).

**Comment by chris-belcher** [comment]
We can see the last travis run was #521 on 8th May. The PR after that #531 on 22nd May did not have a travis run. #531 actually changes something in the tests so I'm guessing the problem is there.

**Comment by AdamISZ** [comment]
@chris-belcher I was originally thinking that was impossible (because there isn't even a trigger/start), but I was forgetting that there is a config file. I will take another look.

**Comment by AdamISZ** [comment]
Hmm. #531 does nothing to travis config. I'll try to dig around in the travis website, maybe some settings changed somehow.

**Comment by AdamISZ** [comment]
https://travis-ci.org/JoinMarket-Org/joinmarket/requests : potential abuse detected, contact support, it says

I fired them an email. Maybe too much resource usage, just a guess.

**Comment by AdamISZ** [comment]
No response yet, but the obvious occurred to me this morning: they probably have a flag based on the fact that the test script uses bitcoin. Hopefully can explain to them that it only instantiates regtest mode, if that supposition is correct.

**Comment by AdamISZ** [comment]
Response, much as expected, seems they will switch back on shortly:

>I'm sorry for the issue. This is a part of our abuse prevention system, which blocks repo if it looks like someone is trying to mine bitcoins. It's not a very sophisticated check, so often we have false positives. I looked at your repo and it looks like a legitimate usage, so I whitelisted you in our system, now the builds should run correctly.

**Comment by chris-belcher** [comment]
That raises the question, are we the only project on github that uses bitcoin -regtest for automated testing?

**Comment by AdamISZ** [comment]
I don't think so; I think I saw bitcore from a google search. Anyway, this is fixed now, closing.
