### ISSUE TITLE
reorganize and abstract yield generator code

### ISSUE THREAD

**Issue by raedah** [JoinMarket-Org/joinmarket#561]
This is a tracking issue.

There is lots of code duplication in the yield generators currently. Actually most of the code outside of create_my_orders is dups. We need to modularize the ygs so that there is a single yield generator base class which is part of the /joinmarket/ lib, and perhaps a shared functions lib for the ygs. At that point, it would should be very easy for a user to grab and add yg addons from another repo. It would be easier to get involved as the yg code would be much more compact to read. A separate repository for yg variations could be maintained, while still providing a sensible default yg for the main joinmarket project that is as turnkey as possible. Also part of this is the mixdepth selection code that can be optimized for the best possible privacy.

**Comment by AdamISZ** [comment]
I think it goes without saying that I fully support this :)


Re: structure, I think @ghtdak liked the idea (and it makes perfect sense) of having something like a `scripts/` subdirectory inside the joinmarket module. They could be base script types and then customisations could extend them.

Having it as a separate package/module could also make sense (which of course would import `joinmarket` or `joinmarket_core` or whatever).

**Comment by AdamISZ** [comment]
Released into 0.2
