### ISSUE TITLE
txfee list index out of range

### ISSUE THREAD

**Issue by raedah** [JoinMarket-Org/joinmarket#572]
from yg
2016-06-11 20:25:41,331 [MainThread  ] [ERROR]  list index out of range
Traceback (most recent call last):
  File "/home/b/joinmarket/joinmarket/irc.py", line 315, in check_for_orders
    txfee = _chunks[4]
IndexError: list index out of range

**Comment by AdamISZ** [comment]
Weird; must be an old version? First, check_for_orders is now in message_channel.py on latest dev, but also: even on latest master, we have a try/except IndexError wrapping that:

https://github.com/JoinMarket-Org/joinmarket/blob/master/joinmarket/irc.py#L319

(it's in message_channel now but it's the same code)

**Comment by raedah** [comment]
yes, could be old.
