### ISSUE TITLE
error: [Errno 110] Connection timed out - irc.py

### ISSUE THREAD

**Issue by HamishMacEwan** [JoinMarket-Org/joinmarket#580]
Hi,

After days of stable operation, neither yield-* nor ob-watcher will successfully connect to the irc host.

<strike>Can no longer connect to joinmarket-pit host via irssi either.</strike />
Can connect to joinmarket-pit host via irssi.
Any suggestions?

**Comment by Onefox** [comment]
Irc has a problem, the order book is also down.
https://joinmarket.me/ob/

**Comment by HamishMacEwan** [comment]
Problem appears to have passed.
