### ISSUE TITLE
Sometimes 'is_spent' doesnt appear in the blockr dict

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#585]
This line 

https://github.com/JoinMarket-Org/joinmarket/blob/66bd67a58a7fc242393a767edd478dd6258ec0ff/joinmarket/blockchaininterface.py#L383

should read

if 'is_spent' in vout and vout['is_spent'] == 1:

There have been reports of crashes where this key didnt exist

**Comment by OverlordQ** [comment]
Typo in this. that should be `vout['is_spent']` not `in_spent`

**Comment by chris-belcher** [comment]
Fixed, thanks.

**Comment by AdamISZ** [comment]
This is merged see: https://github.com/JoinMarket-Org/joinmarket/blob/master/joinmarket/blockchaininterface.py#L382 (sorry I forget which commit). Closing.
