### ISSUE TITLE
Running it in the background?

### ISSUE THREAD

**Issue by Rocks333** [JoinMarket-Org/joinmarket#591]
Since I don't have linux, I'm running it on a VPS.
Is there a way to keep it running even if I disconnect from the VPS for a while?

**Comment by chris-belcher** [comment]
This is a linux question rather than joinmarket. But still interesting to know.

I use screen. Start screen which gives you a terminal. Press `ctrl+a + d` to detach, use `screen -r` to reattach.

**Comment by Rocks333** [comment]
I'm using it on a VPS so I have only terminal, no GUI

**Comment by chris-belcher** [comment]
screen is a command line application

**Comment by Rocks333** [comment]
WOAH this is great!
For anyone else newbie like me, just read that and you are set. Screen is awesome! 
http://www.tecmint.com/screen-command-examples-to-manage-linux-terminals/

**Comment by AdamISZ** [comment]
screen is awesome, agreed :) Although there's a minor annoyance with back-scroll. Anyway, this seems to be a decent solution, in the absence of other suggestions, closing.

**Comment by K1773R** [comment]
Go to copy mode to back scroll via `Ctrl + A   ESC` then you can browse with up/down or page-up/down. To leave this mode, press `ESC` again.

**Comment by AdamISZ** [comment]
Cool thanks for the tip!
