### ISSUE TITLE
Stop using Bitcoin Core's accounts

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#592]
The Core development team intend to remove the accounts feature. JoinMarket uses accounts as labels in case people use many joinmarket wallets with one wallet.dat, or use their wallet.dat for other things.

An alternative to accounts is to check whether an address or transaction appears in a list of joinmarket wallet addresses.

Also then we could close #70

**Comment by btcdrak** [comment]
See Bitcoin Core pull 7729

**Comment by inaltoasinistra** [comment]
this issue is obsolete

**Comment by AdamISZ** [comment]
And this repo is dormant :)
