### ISSUE TITLE
cannot connect to IRC channel since yesterday

### ISSUE THREAD

**Issue by enkumber** [JoinMarket-Org/joinmarket#604]
Yield generator basic cannot connect to IRC since yesterday: 

File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -3] Temporary failure in name resolution

AttributeError("'IRCMessageChannel' object has no attribute 'fd'",)
2016-08-16 10:39:22,785 [MainThread  ] [DEBUG]  disconnected irc

**Comment by AlexCato** [comment]
Seems to be a misconfigured cyberguerrilla configuration. More details here:
https://www.reddit.com/r/joinmarket/comments/4xzxay/couldnt_connect_to_irc_edited_the_etchosts_file/
