### ISSUE TITLE
wallet-tool showutxos should show tries

### ISSUE THREAD

**Issue by eduard6** [JoinMarket-Org/joinmarket#656]
wallet-tool `showutxos` should include the number of tries for each utxo. This allows knowing that a wallet has used all of its tries and needs to be split or add external utxos.

Example:
```
$ python wallet-tool.py wallet.json showutxos -p
{
    "<txid>:8": {
        "privkey": "<privkey>", 
        "value": <value>, 
        "address": "<address>",
        "tries": 0
    }, 
    "<txid>:2": {
        "privkey": "<privkey>",
        "value": <value>,
        "address": "<address>"
        "tries": 3
    }, 
}
```

**Comment by AdamISZ** [comment]
Great thought, thanks.

If anyone else would like to do this that'd be fantastic.

**Comment by chris-belcher** [comment]
I'd recommend we actually make something like this the default. Bitcoin addresses should only be shown if they're unused and ready to receive money.

I've written about it here #259 that it would also discourage address reuse.

**Comment by AdamISZ** [comment]
@chris-belcher aren't you talking about something else there though? This is about sourcing commitments. At the moment commitments.json stores used commitments, but it doesn't help a user to know which utxos those commitments were sourced from, nor how many tries are left on each utxo.

**Comment by chris-belcher** [comment]
Yes you're right. I thought OP was proposing a new wallet-tool method called `showutxos`, didn't realise it already existed.

**Comment by eduard6** [comment]
I have the code and will do PR in couple days.

**Comment by AdamISZ** [comment]
@eduard6 great, thanks, if you have any Qs don't hesitate to ask.

**Comment by AdamISZ** [comment]
Implemented and merged, thanks.
