### ISSUE TITLE
Make wallet-tool suggest walletname when wallet already exists

### ISSUE THREAD

**Issue by Empty2k12** [JoinMarket-Org/joinmarket#678]
Currently if you do
`python wallet-tool.py generate`

It will ask
`Input wallet file name (default: wallet.json)`

If `wallet.json` exists, it should choose `wallet1.json` as the default name. If `wallet1.json` exists it should be `wallet2.json`....

**Basically the naming sheme for the default wallet should be `wallet{n+1}.json` if `n` exists.**

**Comment by juscamarena** [comment]
Seems simple enough.

**Comment by juscamarena** [comment]
Can someone close this?
