### ISSUE TITLE
docs: txfee explanation of percentage does not make sense

### ISSUE THREAD

**Issue by ian-kelling** [JoinMarket-Org/joinmarket#697]
https://github.com/JoinMarket-Org/joinmarket/wiki/Running-a-Yield-Generator:
"Meaning of fields:

txfee. The yield generators contribution to the miner fee. Too low and your coins may be locked up unconfirmed for some time. Too high and your earnings will be low. You may wish to deliberately set this much lower than 0.2% to ensure you'll get a join sooner."

txfee is an absolute value, and there is no reference to any other value, so setting it lower than 0.2% does not make sense. Perhaps this sentence should be part of the bullet for cjfee_r?

**Comment by chris-belcher** [comment]
Thank you, I've removed that part.

Not added any more detailed explanation because right now there are perverse incentives between makers and takers about miner fees, so one day soon the structure of offers will change.
