### ISSUE TITLE
can't import uncompressed private keys

### ISSUE THREAD

**Issue by alexmat** [JoinMarket-Org/joinmarket#738]
python wallet-tool.py -M 0 wallets/wallet.json importprivkey

...

Traceback (most recent call last):
  File "/home/bitcoin/joinmarket-0.2.3/wallet-tool.py", line 339, in <module>
    vbyte=get_p2pk_vbyte()).decode('hex')[:-1]
  File "/home/bitcoin/joinmarket-0.2.3/bitcoin/secp256k1_main.py", line 147, in from_wif_privkey
    raise Exception("Compressed private key is not 33 bytes")
Exception: Compressed private key is not 33 bytes

**Comment by AdamISZ** [comment]
This is not a bug, it was a deliberate decision not to support it (on my part). Apologies for the inconvenience, but I wanted to limit the complexity of the Bitcoin key support (for safety).

**Comment by alexmat** [comment]
Makes sense. Is there an easy way to convert an uncompressed key to a
compressed one that you would recommend?

**Comment by AdamISZ** [comment]
No, funds stored at an address corresponding to an uncompressed pubkey are not redeemable via the address corresponding to the compressed representation of the same pubkey; same key, different address.

Spend the funds out of the key with the uncompressed keys. This is always the right thing to do. Yes, it's possible to save fees by missing that step, but you'd be complicating the use of joinmarket that way, I wouldn't do it. If the amount is too small, best just not to import it probably.

**Comment by alexmat** [comment]
Understood, thanks for the explanation.
