### ISSUE TITLE
Add anti-fee-sniping nLockTime to joinmarket transactions

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#755]
See discussion here https://github.com/bitcoin/bitcoin/pull/2340 and https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2013-February/002185.html and 

Bitcoin Core already does this.

Right now it wouldn't have any effect at all, but in the far-future when bitcoin mining relies only on fees it would be very good. Today it's not too hard to implement and would serve as a good example to any other wallet software. This could be easily done at the same time as #715

**Comment by undeath** [comment]
nLockTime is ignored if RBF is not allowed, which is the case for all joinmarket transactions. Using nLockTime wouldn't make difference unless I'm missing something.

**Comment by the9ull** [comment]
> nSequence <= 0x7fffffff which in turn would again enable RBF

RBF is enabled with nSequence **<** 0x7fffffff

**Comment by inaltoasinistra** [comment]
does this feature create a privacy leak? This would give some information on the runned joinmarket version, and this would reduce the anonimity set.

could this create other privacy problems?

**Comment by AdamISZ** [comment]
@inaltoasinistra Please discuss in joinmarket-clientserver, this repo is dormant.
