### ISSUE TITLE
blockr.io is not working anymore

### ISSUE THREAD

**Issue by kristapsk** [JoinMarket-Org/joinmarket#758]
It just redirects to Coinbase. Default block explorer should be changed to something else.

**Comment by AdamISZ** [comment]
Yes, this has not yet been edited in the software; all references should be removed, the interface code can be removed also; the non-Core alternatives are not sufficiently reliable to be recommended though.

In the new segwit [version](https://github.com/Joinmarket-Org/joinmarket-clientserver) Bitcoin Core is currently required; it's likely the electrum server interface will be added shortly as an alternative (although it will always be strongly recommended to use Bitcoin Core). You can also try that electrum server alternative interface here in this version, but it's flaky (at best it's OK for doing single sendpayment joins, and even then you may need to restart it a number of times).

**Comment by kristapsk** [comment]
Not a problem for me, actually, I use Bitcoin Core for my node. Just noticed blockr.io not working and filled issue.

BTW, still using this old version, haven't yet managed to get clientserver version working on Gentoo Linux, what I use on all my boxes.

**Comment by AdamISZ** [comment]
@kristapsk have you tried installing from master rather than release? I ask because @fivepiece did a serious install script upgrade, should be more robust and work on a broader set of distros. If that doesn't work feel free to let us know what the issue/failure is, thanks.

**Comment by AdamISZ** [comment]
Although i know nothing about gentoo, so the suggestion may ve irrelevant; if thats the case the info in docs/INSTALL.md may or may not be useful.

**Comment by kristapsk** [comment]
I tried with v0.3.0, will check master. Sooner or later will get it working, just need to find some free time for that.
