### ISSUE TITLE
Failed to load wallet, error message: NameError("global name 'SegwitWallet' is not defined",)

### ISSUE THREAD

**Issue by Rocks333** [JoinMarket-Org/joinmarket#775]
When I run the tumbler (python tumbler.py wallet.json   addresses....) I get the following error

`Enter wallet decryption passphrase: 

Failed to load wallet, error message: NameError("global name 'SegwitWallet' is not defined",)
`

**Comment by AdamISZ** [comment]
You've opened the issue in the wrong repo :)

But no matter, this one is simple: this is a bug that was introduced in a commit a couple of weeks ago, and was spotted and fixed a couple of days ago. If you do `git pull` on the [right repo](https://github.com/Joinmarket-Org/joinmarket-clientserver), it should be fixed.
