### ISSUE TITLE
Agora throttling due to "Flooding"

### ISSUE THREAD

**Issue by HamishMacEwan** [JoinMarket-Org/joinmarket#779]
Is this a problem?

`(unhandled) noticed:  agora.anarplex.002 J52Raog1Tviq5hmJ *** Message to J5ExeCkWkoQnLkYZ throttled due to flooding`

Does the message eventually make it through?

**Comment by AdamISZ** [comment]
Wrong repo. Please reopen on the other one.

**Comment by HamishMacEwan** [comment]
Doh!
