### ISSUE TITLE
Support cookie authentication for local node

### ISSUE THREAD

**Issue by mmazi** [JoinMarket-Org/joinmarket#781]
Currently only user/password authentication method seems to be supported. The cookie method is more user-friendly (no config needed).

**Comment by AdamISZ** [comment]
@mmazi the current code is at https://github.com/Joinmarket-Org/joinmarket-clientserver (as it says at the top of the README, here). That code supports cookie auth and has done so since v0.3.4. Let us know in that repo if there's still an issue.

**Comment by mmazi** [comment]
Oh, I was sloppy checking this. Thanks.
