### ISSUE TITLE
Create landing page and documentation website

### ISSUE THREAD

**Issue by clay-v** [JoinMarket-Org/joinmarket#786]
JoinMarket needs a simple landing page with the most important links to how to downlaod and get started with it the fastest way possible. I can contribute with a basic website that will have:
- brief description
- links to download and signatures
- chart of the orderbook

A nice looking documentation site is also in need. I can start a simple one with VuePress that should improve the state of things.

I think that the documentation website could be built on https://github.com/JoinMarket-Org/JoinMarket-Docs but the landing page would need a repo of its own.

How can I proceed with this project?

**Comment by AdamISZ** [comment]
Please re-open on joinmarket-clientserver, see README.

**Comment by clay-v** [comment]
My mistake. I thought I had made sure I was on the correct repo.
