### ISSUE TITLE
Recover not scanning enough internal addresses?

### ISSUE THREAD

**Issue by ZmnSCPxj** [JoinMarket-Org/joinmarket#791]
So I wanted to try out the fidelity bonds thing, and I had a long-running maker and decided to upgrade.

According to the docs, the procedure is to use the `wallet-tool.py recover` and give the original seed words and instead this time indicate to use a fidelity bond wallet.  So I moved my existing `wallet.jmdat` to `wallet_backup.jmdat` and did a recover.

When I first did `wallet-tool.py wallet.jmdat` it told me to trigger a rescan on `bitcoin-cli`, which I did. While it was rescanning, doing a `wallet-tool.py wallet_backup.jmdat` showed the expected amount, while doing a `wallet-tool.py wallet.jmdat` gave only a tiny amount that I had recently moved into the wallet.

Unfortunately for me, once the `bitcoind` rescan had completed, `wallet-tool.py wallet.jmdat` did not show all my expected funds.  Worse, `wallet-tool.py wallet_backup.jmdat` had somehow *also* lost funds.  Both have the same seed words but diverge on the amount they report.

I have done `wallet-tool.py wallet.jmdat -g 500` but funds are still missing.

By my memory, the internal addresses had reached up to something like `m/84'/0'/0'/1/300` or thereabouts.  Setting the gap limit to 500 or so seems to work only on the external addresses, not the internal addresses.  Is there a way to force a proper rescan recovery with the gap limit applying to the internal addresses?  Is there a convenient way for me to get the address derivation for the internal addresses?

**Comment by ZmnSCPxj** [comment]
Hmm, `wallet-tool.py wallet.jmdat displayall -g 500` seems to have gotten everything.  Subsequent `wallet-tool.py wallet.jmdat` seems to have gotten all the funds recovered again.

This could probably be better-documented....

Closing.

**Comment by AdamISZ** [comment]
@ZmnSCPxj please note this repo is not the active Joinmarket one (hasn't been for several years). I will archive it now so people no longer make the mistake.

Please do feel free to open issues at https://github.com/Joinmarket-Org/joinmarket-clientserver .
